// The Deception Table — content data.
export const DECK = [
  // ---- ORIGINAL 12 (expanded) ----
  { secret:"Doctor", hint:"Hospital",
    obvious:["stethoscope","diagnosis","prescription","surgeon","scrubs","defibrillator","pediatrics","oncology","ER","clinic"],
    medium:["patient","checkup","fever","white coat","appointment","waiting room","trust","hands","charts","nurse"],
    subtle:["friendly","calm","bandage","routine","exam","healing","care","stitches","gown","mask"],
    bluff:["medicine","emergency","bed","corridor","ambulance","pain","recovery","visitor","night shift","pharmacy"] },
  
  { secret:"Pirate", hint:"Ocean",
    obvious:["parrot","eyepatch","plunder","cutlass","cannon","skull","captain","chest","treasure map","peg leg"],
    medium:["treasure","ship","island","rum","crew","sail","horizon","storm","dock","freedom"],
    subtle:["map","waves","salt","deep","tide","harbor","wind","blue","voyage","fish"],
    bluff:["sailing","hunt","gold","coins","compass","moonlight","pirate","shipwreck","cave","shark"] },

  { secret:"Wedding", hint:"Party",
    obvious:["bride","vows","groom","bouquet","aisle","cake","ring","dress","toast","first dance"],
    medium:["family","promise","tears","photos","dance","guests","celebration","invitation","gift","speech"],
    subtle:["music","night","balloons","flowers","smile","love","forever","joy","veil","champagne"],
    bluff:["ceremony","reception","honeymoon","flowers","priest","witness","wedding","dinner","cake cutting","applause"] },

  { secret:"Vampire", hint:"Night",
    obvious:["fangs","coffin","garlic","bloodsucker","bat","castle","immortal","pale","stake","sunlight"],
    medium:["blood","mirror","invitation","thirst","old","cape","dark","moon","sleep","shadow"],
    subtle:["cold","stars","silence","fear","dream","black","creature","mist","grave","ancient"],
    bluff:["night","hunt","curse","undead","crypt","vampire","bite","victim","spirit","wraith"] },

  { secret:"Library", hint:"Quiet",
    obvious:["bookshelf","librarian","borrow","catalog","reading","silence","study","pages","whisper","dust"],
    medium:["books","lamp","corner","peace","calm","room","chair","thinking","alone","focus"],
    subtle:["evening","soft","still","quiet","knowledge","learning","story","tome","ink","paper"],
    bluff:["read","study","silence","learning","words","author","chapter","library","card","shelf"] },

  { secret:"Circus", hint:"Show",
    obvious:["clown","trapeze","ringmaster","juggler","tent","acrobat","lion","tickets","popcorn","spotlight"],
    medium:["travel","applause","danger","sawdust","caravan","stage","audience","lights","performance","music"],
    subtle:["laughter","costume","crowd","act","curtain","magic","animals","balancing","smile","wonder"],
    bluff:["circus","entertainment","thrill","amazing","showtime","tricks","clapping","colors","carnival","fun"] },

  { secret:"Winter", hint:"Cold",
    obvious:["snowman","blizzard","icicle","frostbite","snow","ice","scarf","fireplace","sled","freezing"],
    medium:["wind","jacket","shiver","grey","hot tea","gloves","numb","weather","indoors","boots"],
    subtle:["silence","white","breath","early dark","cold","frost","chill","huddle","solitude","still"],
    bluff:["ice","snow","cold","frozen","storm","winter","freeze","hibernate","flurry","chill"] },

  { secret:"Prison", hint:"Locked",
    obvious:["inmate","warden","cellblock","parole","bars","escape","guard","sentence","yard","gate"],
    medium:["time","walls","routine","letters","numbers","key","door","chain","waiting","inside"],
    subtle:["alone","cage","freedom","silence","stone","isolation","regret","count","sleep","shadow"],
    bluff:["prison","jail","crime","criminal","trial","judge","convict","captivity","behind bars","discipline"] },

  { secret:"Desert", hint:"Hot",
    obvious:["cactus","camel","oasis","dune","sand","sun","thirst","mirage","nomad","burning"],
    medium:["dry","summer","sweat","shade","water","yellow","endless","heatwave","noon","gold"],
    subtle:["empty","wind","stars","distance","dust","solitude","vista","silence","blazing","stone"],
    bluff:["desert","hot","sun","sandstorm","cactus","wilderness","barren","travel","explorer","adventure"] },

  { secret:"Detective", hint:"Crime",
    obvious:["magnifying glass","sleuth","deduction","trench coat","clues","mystery","suspect","case","alibi","witness"],
    medium:["questions","notebook","rain","instinct","shadows","police","thief","victim","weapon","scene"],
    subtle:["night","danger","secret","motive","trail","truth","lie","fingerprint","cameras","stakeout"],
    bluff:["detective","case","clue","investigation","murder","mystery","search","dark","city","evidence"] },

  { secret:"Bakery", hint:"Morning",
    obvious:["croissant","baker","sourdough","oven mitts","bread","oven","flour","pastry","dough","fresh"],
    medium:["warm","smell","early","queue","corner shop","coffee","breakfast","sunrise","routine","sweet"],
    subtle:["paper bag","street","open","first light","fresh baked","butter","yeast","crust","muffin","patisserie"],
    bluff:["bakery","bread","cake","pastry","delicious","morning","baking","yeast","flour","cookies"] },

  { secret:"Volcano", hint:"Mountain",
    obvious:["lava","eruption","magma","crater","ash","smoke","island","heat","rumble","peak"],
    medium:["climb","rocks","high","clouds","steep","view","stone","summit","trail","fire"],
    subtle:["sleeping","red","pressure","warning","ancient","deep","rumble","fissure","explosion","molten"],
    bluff:["volcano","mountain","fire","eruption","lava","ash","smoke","peak","crater","stone"] },

  // ---- 40 NEW THEMES ----
  { secret:"Knight", hint:"Castle",
    obvious:["sword","armor","shield","lance","horse","tournament","king","queen","battle","charge"],
    medium:["honor","loyalty","duty","squire","training","war","enemy","capture","tower","flag"],
    subtle:["siege","crown","fortress","brave","knight","steed","duel","guard","oath","castle"],
    bluff:["knight","castle","battle","armor","shield","sword","king","queen","horse","war"] },

  { secret:"Witch", hint:"Cauldron",
    obvious:["broomstick","potion","spellbook","crystal ball","brew","candle","incantation","familiar","herbs","moon"],
    medium:["circle","omen","magic","curse","dark","flight","forest","raven","cloak","mirror"],
    subtle:["whisper","shadow","spirit","mystic","witchcraft","potion","coven","enchant","fog","star"],
    bluff:["witch","magic","spell","potion","cauldron","crystal","moon","forest","dark","raven"] },

  { secret:"Space", hint:"Stars",
    obvious:["astronaut","rocket","telescope","satellite","planet","star","orbit","moon","galaxy","void"],
    medium:["light years","silence","gravitation","exploration","alien","comet","cosmos","deep","launch","nebula"],
    subtle:["solar","sun","voyage","zero gravity","cosmic","darkness","universe","astronomy","mission","crew"],
    bluff:["space","rocket","star","planet","astronaut","galaxy","orbit","moon","sun","explore"] },

  { secret:"Jungle", hint:"Wild",
    obvious:["tiger","parrot","python","waterfall","canopy","monkey","moss","orchid","river","green"],
    medium:["humidity","vines","shelter","mist","fern","adventure","creature","dense","earth","rain"],
    subtle:["shadow","sound","cave","wild","deep","exotic","sunlight","jungle","trek","wilderness"],
    bluff:["jungle","forest","tiger","parrot","river","canopy","monkey","green","wild","adventure"] },

  { secret:"Ghost", hint:"Spirit",
    obvious:["apparition","phantom","ectoplasm","medium","haunted","whisper","shadow","cold spot","chain","fear"],
    medium:["footsteps","memory","sudden chill","unfinished","flicker","dead","scream","darkness","creak","old house"],
    subtle:["ominous","terror","void","tomb","spirit","glimpse","supernatural","haunting","echo","soul"],
    bluff:["ghost","haunted","spirit","phantom","darkness","fear","scream","old house","shadow","whisper"] },

  { secret:"Casino", hint:"Risky",
    obvious:["roulette","jackpot","poker","blackjack","chips","dice","cards","bet","high stakes","dealer"],
    medium:["luck","bluff","tension","system","tell","risk","winner","loser","money","game"],
    subtle:["turn","watch","silence","pressure","strategy","gamble","odds","cheat","green felt","casino"],
    bluff:["casino","poker","roulette","dice","chips","bet","luck","dealer","winner","money"] },

  { secret:"Theater", hint:"Stage",
    obvious:["spotlight","curtain call","monologue","applause","script","costume","backstage","rehearsal","makeup","actor"],
    medium:["emotion","timing","breath","mask","improvisation","acting","stage","role","scene","exit"],
    subtle:["perform","crowd","lights","voice","mirror","drama","audience","character","dialogue","play"],
    bluff:["theater","stage","actor","script","curtain","applause","performance","lights","role","play"] },

  { secret:"Maze", hint:"Labyrinth",
    obvious:["minotaur","dead end","labyrinth","thread","twist","turn","hedge","center","puzzle","mirror"],
    medium:["choice","echo","way","solution","path","corner","dark","wind","confusion","stone"],
    subtle:["exit","cage","chase","trap","enclosed","maze","loop","spiral","break","lost"],
    bluff:["maze","labyrinth","path","turn","wall","dead end","confusion","twist","lost","puzzle"] },

  { secret:"School", hint:"Classroom",
    obvious:["blackboard","textbook","teacher","exam","lesson","student","desk","bell","grade","homework"],
    medium:["learn","knowledge","subject","math","science","history","reading","writing","study","class"],
    subtle:["friends","playground","late","tardy","library","focus","curiosity","school","notebook","pen"],
    bluff:["school","teacher","student","class","lesson","exam","learn","grade","desk","homework"] },

  { secret:"Forest", hint:"Woods",
    obvious:["oak","pine","moss","stream","deer","wolf","tree","canopy","mushroom","trail"],
    medium:["green","peaceful","shade","quiet","earth","wild","camp","hike","shelter","nature"],
    subtle:["listen","still","light","shadow","forest","solitude","animal","wood","bed","fern"],
    bluff:["forest","tree","green","deer","wolf","trail","camp","hike","nature","peaceful"] },

  { secret:"Castle", hint:"Kingdom",
    obvious:["king","queen","throne","armor","crown","knight","moat","drawbridge","tower","kingdom"],
    medium:["royal","court","siege","banner","stone","hall","guard","jester","feast","war"],
    subtle:["power","history","ancient","heritage","castle","keep","fortress","noble","secret passage","heir"],
    bluff:["castle","king","queen","knight","crown","throne","armor","moat","royal","tower"] },

  { secret:"Ocean", hint:"Sea",
    obvious:["wave","tide","coral","shark","dolphin","whale","sail","deep","coast","seashell"],
    medium:["blue","salt","wind","horizon","voyage","island","reef","current","marine","water"],
    subtle:["freedom","vast","calm","storm","ocean","seafarer","tranquil","abyss","surf","marine"],
    bluff:["ocean","sea","wave","tide","shark","dolphin","sail","deep","blue","coast"] },

  { secret:"Mountain", hint:"Peak",
    obvious:["summit","snow","cliff","trek","rock","cloud","ridge","steep","view","ascent"],
    medium:["climb","cold","wind","height","trail","stone","silence","peak","adventure","granite"],
    subtle:["above","still","mountain","wilderness","air","majesty","crest","exposure","edge","ascend"],
    bluff:["mountain","peak","snow","climb","rock","summit","trek","cliff","view","cold"] },

  { secret:"Farm", hint:"Countryside",
    obvious:["tractor","barn","cow","harvest","wheat","plow","chicken","horse","hay","field"],
    medium:["sunrise","soil","apple","apple","orchard","country","crops","granary","farmhouse","homestead"],
    subtle:["quiet","bread","earth","simple","countryside","bale","pasture","silo","vegetable","farm"],
    bluff:["farm","barn","cow","tractor","harvest","wheat","horse","field","chicken","hay"] },

  { secret:"Train", hint:"Railway",
    obvious:["locomotive","carriage","station","tracks","conductor","steam","whistle","platform","depart","arrival"],
    medium:["passenger","route","journey","signal","freight","express","rail","travel","ticket","time"],
    subtle:["window","landscape","distance","night","train","railway","crossing","depot","schedule","seat"],
    bluff:["train","railway","station","tracks","conductor","steam","journey","ticket","passenger","whistle"] },

  { secret:"Airport", hint:"Flight",
    obvious:["plane","pilot","runway","boarding","terminal","takeoff","landing","luggage","passport","gate"],
    medium:["flight","travel","destination","security","departure","arrival","airline","cockpit","control tower","sky"],
    subtle:["connection","delay","boarding pass","overhead","taxi","airport","soar","traveler","itinerary","runway"],
    bluff:["airport","plane","pilot","flight","runway","boarding","travel","terminal","landing","gate"] },

  { secret:"Carnival", hint:"Amusement",
    obvious:["ferris wheel","roller coaster","cotton candy","carousel","games","prize","ticket","ride","clown","scream"],
    medium:["lights","music","crowd","laughter","excitement","carnival","merry","tent","wonder","thrill"],
    subtle:["joy","memory","spinning","glow","carnival","dusk","festival","sweets","awe","dizzy"],
    bluff:["carnival","amusement","ride","game","ticket","cotton candy","ferris wheel","roller coaster","prize","crowd"] },

  { secret:"Castle", hint:"Kingdom",
    obvious:["king","queen","throne","armor","crown","knight","moat","drawbridge","tower","kingdom"],
    medium:["royal","court","siege","banner","stone","hall","guard","jester","feast","war"],
    subtle:["power","history","ancient","heritage","castle","keep","fortress","noble","secret passage","heir"],
    bluff:["castle","king","queen","knight","crown","throne","armor","moat","royal","tower"] },

  { secret:"Beach", hint:"Shore",
    obvious:["sand","sun","wave","seashell","towel","sunglasses","tan","swim","castle","surf"],
    medium:["salt","breeze","summer","relax","shore","beach","coast","tide","vacation","ocean"],
    subtle:["horizon","calm","sandcastle","sunset","beach","bliss","seaside","dune","walk","peace"],
    bluff:["beach","sand","sun","wave","seashell","towel","swim","castle","surf","ocean"] },

  { secret:"Cave", hint:"Underground",
    obvious:["stalactite","stalagmite","darkness","echo","bat","crystal","passage","chamber","cavern","underground"],
    medium:["explore","silence","drip","rock","adventure","cave","hidden","treasure","shadow","subterranean"],
    subtle:["mystery","cool","damp","ancient","shelter","cave","earth","void","secret","echo"],
    bluff:["cave","underground","dark","rock","stalactite","cavern","bat","echo","adventure","hidden"] },

  { secret:"Camping", hint:"Outdoors",
    obvious:["tent","campfire","sleeping bag","hike","marshmallow","trail","wilderness","stars","forest","nature"],
    medium:["light","crackling","roast","adventure","outdoor","camp","lake","mountain","quiet","meadow"],
    subtle:["smell","peace","sky","camping","escape","solitude","pine","camp","embers","rustic"],
    bluff:["camping","tent","campfire","hike","trail","marshmallow","stars","forest","nature","outdoor"] },

  { secret:"Garden", hint:"Bloom",
    obvious:["rose","tulip","daisy","sunflower","garden","flowerbed","petal","soil","bloom","fence"],
    medium:["green","plant","water","grow","prune","garden","butterfly","bee","fragrance","nature"],
    subtle:["peace","pollen","garden","dew","morning","perennial","vine","leaf","tend","blossom"],
    bluff:["garden","flower","rose","tulip","bloom","plant","green","soil","sunflower","petal"] },

  { secret:"Inn", hint:"Tavern",
    obvious:["tavern","ale","hearth","keep","innkeeper","rooms","common room","cellar","kitchen","guest"],
    medium:["warm","gathering","traveler","hospitality","inn","fire","bench","lodging","country","old"],
    subtle:["comfort","quiet","escape","village","inn","roof","night","story","cozy","roaring"],
    bluff:["inn","tavern","ale","hearth","guest","fire","warm","rooms","keeper","traveler"] },

  { secret:"Alchemist", hint:"Lab",
    obvious:["potion","elixir","crystal","vial","brew","distill","fire","glass","alchemy","workbench"],
    medium:["flask","powder","charcoal","simmer","alchemist","reagent","mystic","shelf","study","wisdom"],
    subtle:["recipe","balance","translucent","alchemist","apprentice","phial","catalyst","formation","change","metal"],
    bluff:["alchemist","potion","elixir","crystal","vial","brew","fire","glass","lab","workbench"] },

  { secret:"Cathedral", hint:"Holy",
    obvious:["stained glass","organ","confession","pew","bell","apse","altar","lectern","incense","hymn"],
    medium:["stone","vault","sacred","chant","cathedral","gothic","kneel","roses","homily","reverent"],
    subtle:["quiet","glimmer","incense","cathedral","transept","glory","light","worship","sanctuary","tower"],
    bluff:["cathedral","church","stained glass","organ","bell","altar","pew","stone","holy","chant"] },

  { secret:"Studio", hint:"Art",
    obvious:["canvas","brush","paint","easel","palette","sketch","clay","sculpture","masterpiece","studio"],
    medium:["color","light","composition","create","artist","canvas","exhibit","museum","gallery","inspire"],
    subtle:["unique","imagination","studio","blank canvas","style","texture","vision","frame","curate","flaw"],
    bluff:["studio","art","canvas","brush","paint","easel","palette","sculpture","color","artist"] },

  { secret:"Tavern", hint:"Drinks",
    obvious:["bar","mug","ale","barkeep","stool","tavern","cask","tankard","tap","cellar"],
    medium:["warm","fire","laughter","song","dice","cards","gossip","tavern","patron","keep"],
    subtle:["good company","glow","vintage","tavern","counter","quiet","bottle","journey","tale","mug"],
    bluff:["tavern","bar","ale","mug","barkeep","fire","cask","song","cards","patron"] },

  { secret:"Dungeon", hint:"Dark",
    obvious:["chains","cell","torture","prisoner","warden","darkness","rat","dungeon","rack","dungeon"],
    medium:["damp","stone","guard","iron","escape","solitude","dungeon","oubliette","tunnel","grate"],
    subtle:["silence","echo","cobweb","hopeless","dungeon","lightless","corridor","forgotten","moan","rut"],
    bluff:["dungeon","prison","cell","chains","warden","rat","darkness","stone","guard","escape"] },

  { secret:"Mansion", hint:"Old",
    obvious:["ballroom","chandelier","spiral staircase","parlor","butler","foyer","study","crystal","mansion","portrait"],
    medium:["estate","tapestry","antique","library","silver","hedge","mansion","garden","grand","elegance"],
    subtle:["dust","secret door","echo","shadow","mansion","abandoned","creaking","attic","vaulted","wealth"],
    bluff:["mansion","old","estate","ballroom","chandelier","butler","study","portrait","garden","grand"] },

  { secret:"Fountain", hint:"Water",
    obvious:["plunge","basin","statue","gurgle","courtyard","wish","coin","fountain","moss","sculpture"],
    medium:["flow","clear","cool","fountain","square","feature","bronze","marble","splash","pool"],
    subtle:["night","reflection","fountain","calm","hollow","stone","sunlight","trickle","garden","peace"],
    bluff:["fountain","water","basin","statue","coin","wish","flow","courtyard","splash","bronze"] },

  { secret:"Clocktower", hint:"Time",
    obvious:["bell","mechanism","clock face","spring","gear","tower","hour","chime","time","pendulum"],
    medium:["strike","dusk","dawn","clock","grand","whirr","tower","pavement","shadow","mechanism"],
    subtle:["patina","tick","tock","waiting","tower","moment","timeless","ancient","craft","revolution"],
    bluff:["clocktower","time","bell","gear","clock face","chime","tower","hour","pendulum","strike"] },

  { secret:"Cove", hint:"Harbor",
    obvious:["bay","anchorage","cliff","boat","dinghy","sail","moor","cove","beach","cavern"],
    medium:["shelter","tide","sand","cove","harbor","island","sail","dock","calm","coast"],
    subtle:["privacy","cove","drift","shore","rock","hidden","lagoon","grotto","quiet","inlet"],
    bluff:["cove","harbor","bay","anchorage","boat","cliff","sail","tide","beach","dock"] },

  { secret:"Meadow", hint:"Field",
    obvious:["grass","wildflower","stream","butterfly","meadow","grazing","hill","breeze","clover","sunlit"],
    medium:["green","mountain","cows","sheep","bloom","meadow","flowers","lush","daisies","hive"],
    subtle:["calm","meadow","hay","smell","solitude","golden hour","grazing","quiet","nectar","soft"],
    bluff:["meadow","field","grass","wildflower","butterfly","stream","hill","breeze","grazing","green"] },

  { secret:"Catacombs", hint:"Tomb",
    obvious:["skeleton","tunnel","sarcophagus","niche","lamp","crypt","bone","catacombs","chamber","dust"],
    medium:["dark","echo","passage","stone","forgotten","etched","catacombs","vault","pillar","corridor"],
    subtle:["silence","catacombs","fresco","ghost","lost","epitaph","candle","air","maze","old"],
    bluff:["catacombs","tomb","crypt","skeleton","tunnel","bone","chamber","dark","stone","forgotten"] },

  { secret:"Astrolabe", hint:"Stars",
    obvious:["astrolabe","constellation","pole star","sextant","celestial","planet","star","telescope","reticle","chart"],
    medium:["sphere","armillary","map","navigate","astrolabe","science","brass","ancient","learned","observe"],
    subtle:["precision","wonder","astrolabe","sky","rotation","astronomy","old","star chart","instrument","quest"],
    bluff:["astrolabe","stars","map","navigate","planet","telescope","celestial","chart","constellation","ancient"] },

  { secret:"Siege", hint:"War",
    obvious:["catapult","battering ram","wall","battle","siege","trebuchet","arrow","tower","barricade","assault"],
    medium:["camp","flag","castle","siege","encircle","banner","breach","stone","morale","engine"],
    subtle:["standoff","tension","siege","dust","supply","flag","horn","relief","armor","assault"],
    bluff:["siege","war","catapult","castle","battle","arrow","tower","wall","camp","flag"] },

  { secret:"Parchment", hint:"Scroll",
    obvious:["parchment","quill","ink","scroll","seal","manuscript","vellum","letter","cursive","parchment"],
    medium:["paper","document","history","parchment","library","artifact","signature","parchment","scrivener","book"],
    subtle:["fragile","yellowed","parchment","hand","ancient","record","copperplate","calf","epistle","archive"],
    bluff:["parchment","scroll","quill","ink","letter","seal","manuscript","vellum","document","old"] },

  { secret:"Forge", hint:"Fire",
    obvious:["forge","anvil","hammer","bellows","iron","spark","blade","tongs","forge","metal"],
    medium:["fire","glow","smoke","strike","ring","forge","smithy","weapon","armor","heat"],
    subtle:["hiss","soot","rhythm","ingot","forge","work","craft","ore","clank","skill"],
    bluff:["forge","fire","anvil","hammer","iron","blade","smithy","heat","spark","weapon"] },

  { secret:"Tomb", hint:"Burial",
    obvious:["sarcophagus","pyramid","pharaoh","hieroglyph","canopic","tomb","stone","chamber","mask","amulet"],
    medium:["crypt","symbol","treasure","tomb","mummy","cracked","shaft","guard","soul","priest"],
    subtle:["eternal","darkness","tomb","rest","echo","preserved","sphinx","sand","gate","oasis"],
    bluff:["tomb","burial","pyramid","pharaoh","sarcophagus","hieroglyph","mummy","crypt","stone","mask"] },

  { secret:"Shrine", hint:"Sacred",
    obvious:["shrine","torii","stone","offering","oracle","shrine","lantern","bowing","monk","incense"],
    medium:["peace","prayer","rope","whisper","shrine","guardian","sacred","climb","wood","gate"],
    subtle:["solemn","shrine","light","stillness","vow","bloom","footsteps","chime","spirit","threshold"],
    bluff:["shrine","sacred","stone","offering","torii","lantern","prayer","monk","incense","peace"] },

  { secret:"Moat", hint:"Water",
    obvious:["drawbridge","moat","water","defense","castle","gate","reflection","crocodile","still","wall"],
    medium:["wet","deep","barrier","reflection","moat","dark","rock","fish","lily","edge"],
    subtle:["silence","moat","trap","shadow","old","stagnant","stone","abandon","echo","cool"],
    bluff:["moat","water","drawbridge","castle","defense","gate","wall","wet","deep","barrier"] },

  { secret:"Crypt", hint:"Dungeon",
    obvious:["crypt","coffin","bone","skeleton","altar","torch","dust","cobweb","tombstone","skull"],
    medium:["shroud","chamber","candle","dark","crypt","echo","vault","stone","stalactite","sarcophagus"],
    subtle:["silence","ancient","crypt","forgotten","cold","prayer","wraith","gloom","memory","sanctum"],
    bluff:["crypt","dungeon","coffin","bone","skeleton","altar","dust","candle","tombstone","skull"] },

  { secret:"Library", hint:"Books",
    obvious:["shelf","tome","book","librarian","catalog","lamp","read","archive","dust","card"],
    medium:["study","globe","silence","book","wealth","knowledge","page","letter","history","bibliophile"],
    subtle:["quiet","book","learning","old","binding","ink","paper","character","classic","wisdom"],
    bluff:["library","books","shelf","read","tome","librarian","catalog","lamp","study","knowledge"] },

  { secret:"Observatory", hint:"Sky",
    obvious:["telescope","dome","planet","star","astronomer","observatory","orbit","nebula","chart","cupola"],
    medium:["night","constellation","observatory","instrument","silver","focus","mirror","moon","solar","scope"],
    subtle:["heavens","isolation","observatory","light","awe","dark","gear","roof","science","cosmos"],
    bluff:["observatory","telescope","stars","planet","dome","astronomer","orbit","moon","night","chart"] }
];

export const NPCS = [
  { id:"brute", name:"Gruff Halloran", chip:"#b98a4f", aggression:0.8, caution:0.25, tell:0.25,
    thinkMs:[900,1700] },
  { id:"widow", name:"Madame Vey",     chip:"#9c6b7c", aggression:0.35, caution:0.75, tell:0.12,
    thinkMs:[1600,2600] },
  { id:"fox",  name:"Silky Marlowe",   chip:"#8fa06b", aggression:0.55, caution:0.5,  tell:0.4,
    thinkMs:[700,1400] },
];

export const RULES = {
  seats: 4,
  maxRounds: 4,
  voteUnlockRound: 2,
  handSize: 4,
  weights: { obvious:3, medium:2, subtle:1 },
};