// The Deception Table — content data.
// DECK is keyed by language ("en" / "ku"); each language array is drawn
// from independently at match start (see newMatch() in game.js), so the
// two decks don't need to be identical length or index-aligned — they're
// kept in the same secret order here only for maintainability.
const DECK_EN = [
  // ---- ORIGINAL 12 (expanded) ----
  { secret:"Doctor", hint:"Hospital",
    obvious:["stethoscope","diagnosis","prescription","surgeon","scrubs","defibrillator","pediatrics","oncology","ER","clinic"],
    medium:["patient","checkup","fever","white coat","appointment","waiting room","trust","hands","charts","nurse"],
    subtle:["friendly","calm","bandage","routine","exam","healing","care","stitches","gown","mask"],
    bluff:["medicine","emergency","bed","corridor","ambulance","pain","recovery","visitor","night shift","pharmacy"] },

  { secret:"Pirate", hint:"Ocean",
    obvious:["parrot","eyepatch","plunder","cutlass","cannon","skull","captain","chest","treasure map","peg leg"],
    medium:["treasure","ship","island","rum","crew","sail","horizon","storm","dock","freedom"],
    subtle:["map","waves","salt","deep","tide","harbor","wind","blue","voyage","fish"],
    bluff:["sailing","hunt","gold","coins","compass","moonlight","pirate","shipwreck","cave","shark"] },

  { secret:"Wedding", hint:"Party",
    obvious:["bride","vows","groom","bouquet","aisle","cake","ring","dress","toast","first dance"],
    medium:["family","promise","tears","photos","dance","guests","celebration","invitation","gift","speech"],
    subtle:["music","night","balloons","flowers","smile","love","forever","joy","veil","champagne"],
    bluff:["ceremony","reception","honeymoon","flowers","priest","witness","wedding","dinner","cake cutting","applause"] },

  { secret:"Vampire", hint:"Night",
    obvious:["fangs","coffin","garlic","bloodsucker","bat","castle","immortal","pale","stake","sunlight"],
    medium:["blood","mirror","invitation","thirst","old","cape","dark","moon","sleep","shadow"],
    subtle:["cold","stars","silence","fear","dream","black","creature","mist","grave","ancient"],
    bluff:["night","hunt","curse","undead","crypt","vampire","bite","victim","spirit","wraith"] },

  { secret:"Library", hint:"Quiet",
    obvious:["bookshelf","librarian","borrow","catalog","reading","silence","study","pages","whisper","dust"],
    medium:["books","lamp","corner","peace","calm","room","chair","thinking","alone","focus"],
    subtle:["evening","soft","still","quiet","knowledge","learning","story","tome","ink","paper"],
    bluff:["read","study","silence","learning","words","author","chapter","library","card","shelf"] },

  { secret:"Circus", hint:"Show",
    obvious:["clown","trapeze","ringmaster","juggler","tent","acrobat","lion","tickets","popcorn","spotlight"],
    medium:["travel","applause","danger","sawdust","caravan","stage","audience","lights","performance","music"],
    subtle:["laughter","costume","crowd","act","curtain","magic","animals","balancing","smile","wonder"],
    bluff:["circus","entertainment","thrill","amazing","showtime","tricks","clapping","colors","carnival","fun"] },

  { secret:"Winter", hint:"Cold",
    obvious:["snowman","blizzard","icicle","frostbite","snow","ice","scarf","fireplace","sled","freezing"],
    medium:["wind","jacket","shiver","grey","hot tea","gloves","numb","weather","indoors","boots"],
    subtle:["silence","white","breath","early dark","cold","frost","chill","huddle","solitude","still"],
    bluff:["ice","snow","cold","frozen","storm","winter","freeze","hibernate","flurry","chill"] },

  { secret:"Prison", hint:"Locked",
    obvious:["inmate","warden","cellblock","parole","bars","escape","guard","sentence","yard","gate"],
    medium:["time","walls","routine","letters","numbers","key","door","chain","waiting","inside"],
    subtle:["alone","cage","freedom","silence","stone","isolation","regret","count","sleep","shadow"],
    bluff:["prison","jail","crime","criminal","trial","judge","convict","captivity","behind bars","discipline"] },

  { secret:"Desert", hint:"Hot",
    obvious:["cactus","camel","oasis","dune","sand","sun","thirst","mirage","nomad","burning"],
    medium:["dry","summer","sweat","shade","water","yellow","endless","heatwave","noon","gold"],
    subtle:["empty","wind","stars","distance","dust","solitude","vista","silence","blazing","stone"],
    bluff:["desert","hot","sun","sandstorm","cactus","wilderness","barren","travel","explorer","adventure"] },

  { secret:"Detective", hint:"Crime",
    obvious:["magnifying glass","sleuth","deduction","trench coat","clues","mystery","suspect","case","alibi","witness"],
    medium:["questions","notebook","rain","instinct","shadows","police","thief","victim","weapon","scene"],
    subtle:["night","danger","secret","motive","trail","truth","lie","fingerprint","cameras","stakeout"],
    bluff:["detective","case","clue","investigation","murder","mystery","search","dark","city","evidence"] },

  { secret:"Bakery", hint:"Morning",
    obvious:["croissant","baker","sourdough","oven mitts","bread","oven","flour","pastry","dough","fresh"],
    medium:["warm","smell","early","queue","corner shop","coffee","breakfast","sunrise","routine","sweet"],
    subtle:["paper bag","street","open","first light","fresh baked","butter","yeast","crust","muffin","patisserie"],
    bluff:["bakery","bread","cake","pastry","delicious","morning","baking","yeast","flour","cookies"] },

  { secret:"Volcano", hint:"Mountain",
    obvious:["lava","eruption","magma","crater","ash","smoke","island","heat","rumble","peak"],
    medium:["climb","rocks","high","clouds","steep","view","stone","summit","trail","fire"],
    subtle:["sleeping","red","pressure","warning","ancient","deep","rumble","fissure","explosion","molten"],
    bluff:["volcano","mountain","fire","eruption","lava","ash","smoke","peak","crater","stone"] },

  // ---- 40 NEW THEMES ----
  { secret:"Knight", hint:"Castle",
    obvious:["sword","armor","shield","lance","horse","tournament","king","queen","battle","charge"],
    medium:["honor","loyalty","duty","squire","training","war","enemy","capture","tower","flag"],
    subtle:["siege","crown","fortress","brave","knight","steed","duel","guard","oath","castle"],
    bluff:["knight","castle","battle","armor","shield","sword","king","queen","horse","war"] },

  { secret:"Witch", hint:"Cauldron",
    obvious:["broomstick","potion","spellbook","crystal ball","brew","candle","incantation","familiar","herbs","moon"],
    medium:["circle","omen","magic","curse","dark","flight","forest","raven","cloak","mirror"],
    subtle:["whisper","shadow","spirit","mystic","witchcraft","potion","coven","enchant","fog","star"],
    bluff:["witch","magic","spell","potion","cauldron","crystal","moon","forest","dark","raven"] },

  { secret:"Space", hint:"Stars",
    obvious:["astronaut","rocket","telescope","satellite","planet","star","orbit","moon","galaxy","void"],
    medium:["light years","silence","gravitation","exploration","alien","comet","cosmos","deep","launch","nebula"],
    subtle:["solar","sun","voyage","zero gravity","cosmic","darkness","universe","astronomy","mission","crew"],
    bluff:["space","rocket","star","planet","astronaut","galaxy","orbit","moon","sun","explore"] },

  { secret:"Jungle", hint:"Wild",
    obvious:["tiger","parrot","python","waterfall","canopy","monkey","moss","orchid","river","green"],
    medium:["humidity","vines","shelter","mist","fern","adventure","creature","dense","earth","rain"],
    subtle:["shadow","sound","cave","wild","deep","exotic","sunlight","jungle","trek","wilderness"],
    bluff:["jungle","forest","tiger","parrot","river","canopy","monkey","green","wild","adventure"] },

  { secret:"Ghost", hint:"Spirit",
    obvious:["apparition","phantom","ectoplasm","medium","haunted","whisper","shadow","cold spot","chain","fear"],
    medium:["footsteps","memory","sudden chill","unfinished","flicker","dead","scream","darkness","creak","old house"],
    subtle:["ominous","terror","void","tomb","spirit","glimpse","supernatural","haunting","echo","soul"],
    bluff:["ghost","haunted","spirit","phantom","darkness","fear","scream","old house","shadow","whisper"] },

  { secret:"Casino", hint:"Risky",
    obvious:["roulette","jackpot","poker","blackjack","chips","dice","cards","bet","high stakes","dealer"],
    medium:["luck","bluff","tension","system","tell","risk","winner","loser","money","game"],
    subtle:["turn","watch","silence","pressure","strategy","gamble","odds","cheat","green felt","casino"],
    bluff:["casino","poker","roulette","dice","chips","bet","luck","dealer","winner","money"] },

  { secret:"Theater", hint:"Stage",
    obvious:["spotlight","curtain call","monologue","applause","script","costume","backstage","rehearsal","makeup","actor"],
    medium:["emotion","timing","breath","mask","improvisation","acting","stage","role","scene","exit"],
    subtle:["perform","crowd","lights","voice","mirror","drama","audience","character","dialogue","play"],
    bluff:["theater","stage","actor","script","curtain","applause","performance","lights","role","play"] },

  { secret:"Maze", hint:"Labyrinth",
    obvious:["minotaur","dead end","labyrinth","thread","twist","turn","hedge","center","puzzle","mirror"],
    medium:["choice","echo","way","solution","path","corner","dark","wind","confusion","stone"],
    subtle:["exit","cage","chase","trap","enclosed","maze","loop","spiral","break","lost"],
    bluff:["maze","labyrinth","path","turn","wall","dead end","confusion","twist","lost","puzzle"] },

  { secret:"School", hint:"Classroom",
    obvious:["blackboard","textbook","teacher","exam","lesson","student","desk","bell","grade","homework"],
    medium:["learn","knowledge","subject","math","science","history","reading","writing","study","class"],
    subtle:["friends","playground","late","tardy","library","focus","curiosity","school","notebook","pen"],
    bluff:["school","teacher","student","class","lesson","exam","learn","grade","desk","homework"] },

  { secret:"Forest", hint:"Woods",
    obvious:["oak","pine","moss","stream","deer","wolf","tree","canopy","mushroom","trail"],
    medium:["green","peaceful","shade","quiet","earth","wild","camp","hike","shelter","nature"],
    subtle:["listen","still","light","shadow","forest","solitude","animal","wood","bed","fern"],
    bluff:["forest","tree","green","deer","wolf","trail","camp","hike","nature","peaceful"] },

  { secret:"Castle", hint:"Kingdom",
    obvious:["king","queen","throne","armor","crown","knight","moat","drawbridge","tower","kingdom"],
    medium:["royal","court","siege","banner","stone","hall","guard","jester","feast","war"],
    subtle:["power","history","ancient","heritage","castle","keep","fortress","noble","secret passage","heir"],
    bluff:["castle","king","queen","knight","crown","throne","armor","moat","royal","tower"] },

  { secret:"Ocean", hint:"Sea",
    obvious:["wave","tide","coral","shark","dolphin","whale","sail","deep","coast","seashell"],
    medium:["blue","salt","wind","horizon","voyage","island","reef","current","marine","water"],
    subtle:["freedom","vast","calm","storm","ocean","seafarer","tranquil","abyss","surf","marine"],
    bluff:["ocean","sea","wave","tide","shark","dolphin","sail","deep","blue","coast"] },

  { secret:"Mountain", hint:"Peak",
    obvious:["summit","snow","cliff","trek","rock","cloud","ridge","steep","view","ascent"],
    medium:["climb","cold","wind","height","trail","stone","silence","peak","adventure","granite"],
    subtle:["above","still","mountain","wilderness","air","majesty","crest","exposure","edge","ascend"],
    bluff:["mountain","peak","snow","climb","rock","summit","trek","cliff","view","cold"] },

  { secret:"Farm", hint:"Countryside",
    obvious:["tractor","barn","cow","harvest","wheat","plow","chicken","horse","hay","field"],
    medium:["sunrise","soil","apple","apple","orchard","country","crops","granary","farmhouse","homestead"],
    subtle:["quiet","bread","earth","simple","countryside","bale","pasture","silo","vegetable","farm"],
    bluff:["farm","barn","cow","tractor","harvest","wheat","horse","field","chicken","hay"] },

  { secret:"Train", hint:"Railway",
    obvious:["locomotive","carriage","station","tracks","conductor","steam","whistle","platform","depart","arrival"],
    medium:["passenger","route","journey","signal","freight","express","rail","travel","ticket","time"],
    subtle:["window","landscape","distance","night","train","railway","crossing","depot","schedule","seat"],
    bluff:["train","railway","station","tracks","conductor","steam","journey","ticket","passenger","whistle"] },

  { secret:"Airport", hint:"Flight",
    obvious:["plane","pilot","runway","boarding","terminal","takeoff","landing","luggage","passport","gate"],
    medium:["flight","travel","destination","security","departure","arrival","airline","cockpit","control tower","sky"],
    subtle:["connection","delay","boarding pass","overhead","taxi","airport","soar","traveler","itinerary","runway"],
    bluff:["airport","plane","pilot","flight","runway","boarding","travel","terminal","landing","gate"] },

  { secret:"Carnival", hint:"Amusement",
    obvious:["ferris wheel","roller coaster","cotton candy","carousel","games","prize","ticket","ride","clown","scream"],
    medium:["lights","music","crowd","laughter","excitement","carnival","merry","tent","wonder","thrill"],
    subtle:["joy","memory","spinning","glow","carnival","dusk","festival","sweets","awe","dizzy"],
    bluff:["carnival","amusement","ride","game","ticket","cotton candy","ferris wheel","roller coaster","prize","crowd"] },

  { secret:"Castle", hint:"Kingdom",
    obvious:["king","queen","throne","armor","crown","knight","moat","drawbridge","tower","kingdom"],
    medium:["royal","court","siege","banner","stone","hall","guard","jester","feast","war"],
    subtle:["power","history","ancient","heritage","castle","keep","fortress","noble","secret passage","heir"],
    bluff:["castle","king","queen","knight","crown","throne","armor","moat","royal","tower"] },

  { secret:"Beach", hint:"Shore",
    obvious:["sand","sun","wave","seashell","towel","sunglasses","tan","swim","castle","surf"],
    medium:["salt","breeze","summer","relax","shore","beach","coast","tide","vacation","ocean"],
    subtle:["horizon","calm","sandcastle","sunset","beach","bliss","seaside","dune","walk","peace"],
    bluff:["beach","sand","sun","wave","seashell","towel","swim","castle","surf","ocean"] },

  { secret:"Cave", hint:"Underground",
    obvious:["stalactite","stalagmite","darkness","echo","bat","crystal","passage","chamber","cavern","underground"],
    medium:["explore","silence","drip","rock","adventure","cave","hidden","treasure","shadow","subterranean"],
    subtle:["mystery","cool","damp","ancient","shelter","cave","earth","void","secret","echo"],
    bluff:["cave","underground","dark","rock","stalactite","cavern","bat","echo","adventure","hidden"] },

  { secret:"Camping", hint:"Outdoors",
    obvious:["tent","campfire","sleeping bag","hike","marshmallow","trail","wilderness","stars","forest","nature"],
    medium:["light","crackling","roast","adventure","outdoor","camp","lake","mountain","quiet","meadow"],
    subtle:["smell","peace","sky","camping","escape","solitude","pine","camp","embers","rustic"],
    bluff:["camping","tent","campfire","hike","trail","marshmallow","stars","forest","nature","outdoor"] },

  { secret:"Garden", hint:"Bloom",
    obvious:["rose","tulip","daisy","sunflower","garden","flowerbed","petal","soil","bloom","fence"],
    medium:["green","plant","water","grow","prune","garden","butterfly","bee","fragrance","nature"],
    subtle:["peace","pollen","garden","dew","morning","perennial","vine","leaf","tend","blossom"],
    bluff:["garden","flower","rose","tulip","bloom","plant","green","soil","sunflower","petal"] },

  { secret:"Inn", hint:"Tavern",
    obvious:["tavern","ale","hearth","keep","innkeeper","rooms","common room","cellar","kitchen","guest"],
    medium:["warm","gathering","traveler","hospitality","inn","fire","bench","lodging","country","old"],
    subtle:["comfort","quiet","escape","village","inn","roof","night","story","cozy","roaring"],
    bluff:["inn","tavern","ale","hearth","guest","fire","warm","rooms","keeper","traveler"] },

  { secret:"Alchemist", hint:"Lab",
    obvious:["potion","elixir","crystal","vial","brew","distill","fire","glass","alchemy","workbench"],
    medium:["flask","powder","charcoal","simmer","alchemist","reagent","mystic","shelf","study","wisdom"],
    subtle:["recipe","balance","translucent","alchemist","apprentice","phial","catalyst","formation","change","metal"],
    bluff:["alchemist","potion","elixir","crystal","vial","brew","fire","glass","lab","workbench"] },

  { secret:"Cathedral", hint:"Holy",
    obvious:["stained glass","organ","confession","pew","bell","apse","altar","lectern","incense","hymn"],
    medium:["stone","vault","sacred","chant","cathedral","gothic","kneel","roses","homily","reverent"],
    subtle:["quiet","glimmer","incense","cathedral","transept","glory","light","worship","sanctuary","tower"],
    bluff:["cathedral","church","stained glass","organ","bell","altar","pew","stone","holy","chant"] },

  { secret:"Studio", hint:"Art",
    obvious:["canvas","brush","paint","easel","palette","sketch","clay","sculpture","masterpiece","studio"],
    medium:["color","light","composition","create","artist","canvas","exhibit","museum","gallery","inspire"],
    subtle:["unique","imagination","studio","blank canvas","style","texture","vision","frame","curate","flaw"],
    bluff:["studio","art","canvas","brush","paint","easel","palette","sculpture","color","artist"] },

  { secret:"Tavern", hint:"Drinks",
    obvious:["bar","mug","ale","barkeep","stool","tavern","cask","tankard","tap","cellar"],
    medium:["warm","fire","laughter","song","dice","cards","gossip","tavern","patron","keep"],
    subtle:["good company","glow","vintage","tavern","counter","quiet","bottle","journey","tale","mug"],
    bluff:["tavern","bar","ale","mug","barkeep","fire","cask","song","cards","patron"] },

  { secret:"Dungeon", hint:"Dark",
    obvious:["chains","cell","torture","prisoner","warden","darkness","rat","dungeon","rack","dungeon"],
    medium:["damp","stone","guard","iron","escape","solitude","dungeon","oubliette","tunnel","grate"],
    subtle:["silence","echo","cobweb","hopeless","dungeon","lightless","corridor","forgotten","moan","rut"],
    bluff:["dungeon","prison","cell","chains","warden","rat","darkness","stone","guard","escape"] },

  { secret:"Mansion", hint:"Old",
    obvious:["ballroom","chandelier","spiral staircase","parlor","butler","foyer","study","crystal","mansion","portrait"],
    medium:["estate","tapestry","antique","library","silver","hedge","mansion","garden","grand","elegance"],
    subtle:["dust","secret door","echo","shadow","mansion","abandoned","creaking","attic","vaulted","wealth"],
    bluff:["mansion","old","estate","ballroom","chandelier","butler","study","portrait","garden","grand"] },

  { secret:"Fountain", hint:"Water",
    obvious:["plunge","basin","statue","gurgle","courtyard","wish","coin","fountain","moss","sculpture"],
    medium:["flow","clear","cool","fountain","square","feature","bronze","marble","splash","pool"],
    subtle:["night","reflection","fountain","calm","hollow","stone","sunlight","trickle","garden","peace"],
    bluff:["fountain","water","basin","statue","coin","wish","flow","courtyard","splash","bronze"] },

  { secret:"Clocktower", hint:"Time",
    obvious:["bell","mechanism","clock face","spring","gear","tower","hour","chime","time","pendulum"],
    medium:["strike","dusk","dawn","clock","grand","whirr","tower","pavement","shadow","mechanism"],
    subtle:["patina","tick","tock","waiting","tower","moment","timeless","ancient","craft","revolution"],
    bluff:["clocktower","time","bell","gear","clock face","chime","tower","hour","pendulum","strike"] },

  { secret:"Cove", hint:"Harbor",
    obvious:["bay","anchorage","cliff","boat","dinghy","sail","moor","cove","beach","cavern"],
    medium:["shelter","tide","sand","cove","harbor","island","sail","dock","calm","coast"],
    subtle:["privacy","cove","drift","shore","rock","hidden","lagoon","grotto","quiet","inlet"],
    bluff:["cove","harbor","bay","anchorage","boat","cliff","sail","tide","beach","dock"] },

  { secret:"Meadow", hint:"Field",
    obvious:["grass","wildflower","stream","butterfly","meadow","grazing","hill","breeze","clover","sunlit"],
    medium:["green","mountain","cows","sheep","bloom","meadow","flowers","lush","daisies","hive"],
    subtle:["calm","meadow","hay","smell","solitude","golden hour","grazing","quiet","nectar","soft"],
    bluff:["meadow","field","grass","wildflower","butterfly","stream","hill","breeze","grazing","green"] },

  { secret:"Catacombs", hint:"Tomb",
    obvious:["skeleton","tunnel","sarcophagus","niche","lamp","crypt","bone","catacombs","chamber","dust"],
    medium:["dark","echo","passage","stone","forgotten","etched","catacombs","vault","pillar","corridor"],
    subtle:["silence","catacombs","fresco","ghost","lost","epitaph","candle","air","maze","old"],
    bluff:["catacombs","tomb","crypt","skeleton","tunnel","bone","chamber","dark","stone","forgotten"] },

  { secret:"Astrolabe", hint:"Stars",
    obvious:["astrolabe","constellation","pole star","sextant","celestial","planet","star","telescope","reticle","chart"],
    medium:["sphere","armillary","map","navigate","astrolabe","science","brass","ancient","learned","observe"],
    subtle:["precision","wonder","astrolabe","sky","rotation","astronomy","old","star chart","instrument","quest"],
    bluff:["astrolabe","stars","map","navigate","planet","telescope","celestial","chart","constellation","ancient"] },

  { secret:"Siege", hint:"War",
    obvious:["catapult","battering ram","wall","battle","siege","trebuchet","arrow","tower","barricade","assault"],
    medium:["camp","flag","castle","siege","encircle","banner","breach","stone","morale","engine"],
    subtle:["standoff","tension","siege","dust","supply","flag","horn","relief","armor","assault"],
    bluff:["siege","war","catapult","castle","battle","arrow","tower","wall","camp","flag"] },

  { secret:"Parchment", hint:"Scroll",
    obvious:["parchment","quill","ink","scroll","seal","manuscript","vellum","letter","cursive","parchment"],
    medium:["paper","document","history","parchment","library","artifact","signature","parchment","scrivener","book"],
    subtle:["fragile","yellowed","parchment","hand","ancient","record","copperplate","calf","epistle","archive"],
    bluff:["parchment","scroll","quill","ink","letter","seal","manuscript","vellum","document","old"] },

  { secret:"Forge", hint:"Fire",
    obvious:["forge","anvil","hammer","bellows","iron","spark","blade","tongs","forge","metal"],
    medium:["fire","glow","smoke","strike","ring","forge","smithy","weapon","armor","heat"],
    subtle:["hiss","soot","rhythm","ingot","forge","work","craft","ore","clank","skill"],
    bluff:["forge","fire","anvil","hammer","iron","blade","smithy","heat","spark","weapon"] },

  { secret:"Tomb", hint:"Burial",
    obvious:["sarcophagus","pyramid","pharaoh","hieroglyph","canopic","tomb","stone","chamber","mask","amulet"],
    medium:["crypt","symbol","treasure","tomb","mummy","cracked","shaft","guard","soul","priest"],
    subtle:["eternal","darkness","tomb","rest","echo","preserved","sphinx","sand","gate","oasis"],
    bluff:["tomb","burial","pyramid","pharaoh","sarcophagus","hieroglyph","mummy","crypt","stone","mask"] },

  { secret:"Shrine", hint:"Sacred",
    obvious:["shrine","torii","stone","offering","oracle","shrine","lantern","bowing","monk","incense"],
    medium:["peace","prayer","rope","whisper","shrine","guardian","sacred","climb","wood","gate"],
    subtle:["solemn","shrine","light","stillness","vow","bloom","footsteps","chime","spirit","threshold"],
    bluff:["shrine","sacred","stone","offering","torii","lantern","prayer","monk","incense","peace"] },

  { secret:"Moat", hint:"Water",
    obvious:["drawbridge","moat","water","defense","castle","gate","reflection","crocodile","still","wall"],
    medium:["wet","deep","barrier","reflection","moat","dark","rock","fish","lily","edge"],
    subtle:["silence","moat","trap","shadow","old","stagnant","stone","abandon","echo","cool"],
    bluff:["moat","water","drawbridge","castle","defense","gate","wall","wet","deep","barrier"] },

  { secret:"Crypt", hint:"Dungeon",
    obvious:["crypt","coffin","bone","skeleton","altar","torch","dust","cobweb","tombstone","skull"],
    medium:["shroud","chamber","candle","dark","crypt","echo","vault","stone","stalactite","sarcophagus"],
    subtle:["silence","ancient","crypt","forgotten","cold","prayer","wraith","gloom","memory","sanctum"],
    bluff:["crypt","dungeon","coffin","bone","skeleton","altar","dust","candle","tombstone","skull"] },

  { secret:"Library", hint:"Books",
    obvious:["shelf","tome","book","librarian","catalog","lamp","read","archive","dust","card"],
    medium:["study","globe","silence","book","wealth","knowledge","page","letter","history","bibliophile"],
    subtle:["quiet","book","learning","old","binding","ink","paper","character","classic","wisdom"],
    bluff:["library","books","shelf","read","tome","librarian","catalog","lamp","study","knowledge"] },

  { secret:"Observatory", hint:"Sky",
    obvious:["telescope","dome","planet","star","astronomer","observatory","orbit","nebula","chart","cupola"],
    medium:["night","constellation","observatory","instrument","silver","focus","mirror","moon","solar","scope"],
    subtle:["heavens","isolation","observatory","light","awe","dark","gear","roof","science","cosmos"],
    bluff:["observatory","telescope","stars","planet","dome","astronomer","orbit","moon","night","chart"] }
];

// ---- Kurdish Central (Sorani) deck — same 56 cards, same order. ----
// First-pass translation; a native-speaker review pass is recommended
// before shipping, especially for rare/archaic tiles (astrolabe, siege).
const DECK_KU = [
  { secret:"پزیشک", hint:"نەخۆشخانە",
    obvious:["سیتۆسکۆپ","پشکنین","نوسخە","نەشتەرگەر","جلی پزیشکی","کارەبادەری دڵ","منداڵپزیشکی","نەخۆشی سەرەتان","فریاگوزاری","نۆرینگە"],
    medium:["نەخۆش","پشکنین","تای","کەوایەکی سپی","کاتی چاوپێکەوتن","ژووری چاوەڕوانی","متمانە","دەست","خشتەی نەخۆشی","پەرستار"],
    subtle:["دڵسۆز","ئارام","بانداژ","ئاسایی","تاقیکردنەوە","چاکبوونەوە","خەمخواردن","دەرزی","کراس","ماسک"],
    bluff:["دەرمان","فریاگوزاری","قەرەوێڵە","دالان","ئۆتۆمبێلی فریاگوزاری","ئازار","چاکبوونەوە","میوان","نۆرەی شەو","دەرمانخانە"] },

  { secret:"دەریازن", hint:"ئۆقیانوس",
    obvious:["تووتی","چاوپۆشین","تاڵانکردن","شمشێری چەماوە","تۆپ","کاسەسەر","کاپتن","سندوق","نەخشەی گەنجینە","قاچی دار"],
    medium:["گەنجینە","کەشتی","دوورگە","ڕەم","ئەندامانی کەشتی","بادبان","ئاسۆ","ڕەشەبا","بەندەر","ئازادی"],
    subtle:["نەخشە","شەپۆل","خوێ","قووڵایی","مەد و جەزر","بەندەر","با","شین","گەشت","ماسی"],
    bluff:["دەریاوانی","ڕاوکردن","زێڕ","دراو","قوتوپاس","ڕووناکی مانگ","دەریازن","تێکشکانی کەشتی","ئەشکەوت","کوسە"] },

  { secret:"زەماوەند", hint:"ئاهەنگ",
    obvious:["بووک","سوێند","زاوا","دەستە گوڵ","ڕیز","کێک","ئەڵقە","کراسی سپی","پیرۆزبایی","سەماکردنی یەکەم"],
    medium:["خێزان","بەڵێن","فرمێسک","وێنە","سەما","میوان","ئاهەنگ","بانگهێشت","دیاری","وتار"],
    subtle:["مۆسیقا","شەو","بالۆن","گوڵ","پێکەنین","خۆشەویستی","هەتاهەتایی","خۆشی","پۆشاک","شامپاین"],
    bluff:["ئایین","پێشوازی","مانگەسەلی","گوڵ","پیاوی ئایینی","شایەت","زەماوەند","نانی شەو","بڕینی کێک","چەپڵەڕێزان"] },

  { secret:"ڤامپایر", hint:"شەو",
    obvious:["ددان","تابووت","سیر","خوێنمژ","شەمشەمەڵک","قەڵا","نەمر","زەرد","دار تیژ","تیشکی خۆر"],
    medium:["خوێن","ئاوێنە","بانگهێشت","تینوێتی","کۆن","کەپ","تاریک","مانگ","خەو","سێبەر"],
    subtle:["سارد","ئەستێرە","بێدەنگی","ترس","خەون","ڕەش","بوونەوەر","تەم","گۆڕ","دێرین"],
    bluff:["شەو","ڕاوکردن","نەفرەت","نەمر","تاق","ڤامپایر","گاز","قوربانی","ڕۆح","شەبح"] },

  { secret:"کتێبخانە", hint:"بێدەنگی",
    obvious:["ڕەفی کتێب","کتێبخانەوان","قەرزکردن","پێرست","خوێندنەوە","بێدەنگی","خوێندن","لاپەڕە","پچڕپچڕ","تۆز"],
    medium:["کتێب","چرا","کونج","ئارامی","هێمنی","ژوور","کورسی","بیرکردنەوە","تەنیا","تیشکخستنە سەر"],
    subtle:["ئێوارە","نەرم","بێجوڵە","بێدەنگ","زانیاری","فێربوون","چیرۆک","بەرگی گەورە","مرەکەب","کاغەز"],
    bluff:["خوێندنەوە","خوێندن","بێدەنگی","فێربوون","وشە","نووسەر","بەشی کتێب","کتێبخانە","کارت","ڕەف"] },

  { secret:"سیرک", hint:"نمایش",
    obvious:["مەسخەرەباز","تراپیز","سەرۆکی سیرک","بازیدەری تۆپ","چادر","بازیدەر","شێر","بلیت","پۆپکۆرن","تیشکی سەکۆ"],
    medium:["گەشتکردن","چەپڵەڕێزان","مەترسی","تۆزی دار","عەرەبانە","سەکۆ","بینەر","ڕووناکی","پێشاندان","مۆسیقا"],
    subtle:["پێکەنین","جل","خەڵک","کردار","پەردە","جادو","ئاژەڵ","هاوسەنگی","سەرسوڕمان","خۆشی"],
    bluff:["سیرک","خۆشی","توندوتیژی","سەرسوڕهێنەر","کاتی پیشاندان","تڕفەند","چەپڵەڕێزان","ڕەنگ","کارنیڤاڵ","خۆشی"] },

  { secret:"زستان", hint:"سارد",
    obvious:["مرۆڤی بەفری","ڕەشەبای بەفری","بەستەڵەک","سەرمابوون","بەفر","سەهۆڵ","شاڵ","بخاری","سلید","سەرما"],
    medium:["با","کەوا","لەرین","ڕەساس","چای گەرم","دەستکێش","بێهەست","کەشوهەوا","ژوورەوە","پێڵاو"],
    subtle:["بێدەنگی","سپی","هەناسە","تاریکی زوو","سارد","سەرما","لەرزین","کۆبوونەوە","تەنیایی","نەجوڵان"],
    bluff:["سەهۆڵ","بەفر","سارد","بەستراو","ڕەشەبا","زستان","بەستنەوە","خەوی درێژ","بارین","سەرما"] },

  { secret:"زیندان", hint:"قوفڵکراو",
    obvious:["بەندکراو","سەرپەرشتیار","خانەکان","ئازادکردنی مۆڵەتی","میلە","هەڵاتن","پاسەوان","سزا","حەوشە","دەروازە"],
    medium:["کات","دیوار","ڕۆتین","نامە","ژمارە","کلیل","دەرگا","زنجیر","چاوەڕوانی","ژوورەوە"],
    subtle:["تەنیا","قەفەز","ئازادی","بێدەنگی","بەرد","دووربوونەوە","پەشیمانی","ژماردن","خەو","سێبەر"],
    bluff:["زیندان","سزادان","تاوان","تاوانبار","دادگا","دادوەر","بەندکراو","بەندیخانە","لەپشت میلەکان","تەمبێکردن"] },

  { secret:"بیابان", hint:"گەرم",
    obvious:["کاکتاس","وشتر","واحە","لووتکەی خۆڵ","ڕیگ","خۆر","تینوێتی","خەیاڵی چۆل","کۆچەر","سووتان"],
    medium:["وشک","هاوین","ئارەق","سێبەر","ئاو","زەرد","بێکۆتایی","شەپۆلی گەرمی","نیوەڕۆ","زێڕ"],
    subtle:["بەتاڵ","با","ئەستێرە","دووری","تۆز","تەنیایی","دیمەن","بێدەنگی","سووتاو","بەرد"],
    bluff:["بیابان","گەرم","خۆر","ڕەشەبای خۆڵ","کاکتاس","چۆڵەوانی","وشک","گەشتکردن","دۆزەرەوە","سەرکێشی"] },

  { secret:"لێکۆڵەر", hint:"تاوان",
    obvious:["مەزنکەرەوە","لێکۆڵینەوە","کەوای درێژ","شوێن","نهێنی","گومانلێکراو","دۆسیە","ئالیبی","شایەت","تاوان"],
    medium:["پرسیار","دەفتەرچە","باران","هەستکردن","سێبەر","پۆلیس","دز","قوربانی","چەک","شوێنی ڕووداو"],
    subtle:["شەو","مەترسی","نهێنی","هۆکار","شوێنپێ","ڕاستی","درۆ","شوێنی پەنجە","کامێرا","چاودێری"],
    bluff:["لێکۆڵەر","دۆسیە","نیشانە","لێکۆڵینەوە","کوشتن","نهێنی","گەڕان","تاریک","شار","بەڵگە"] },

  { secret:"نانەوایی", hint:"بەیانی",
    obvious:["کرواسان","نانەوا","نانی تڕشاو","دەستکێشی فڕن","نان","فڕن","ئارد","شیرینی","هەویر","تازە"],
    medium:["گەرم","بۆن","زوو","ڕیز","دوکانی گۆشە","قاوە","نانی بەیانی","خۆرهەڵاتن","ڕۆتین","شیرین"],
    subtle:["کیسەی کاغەز","شەقام","کراوە","یەکەم ڕووناکی","تازە ئامادەکراو","کەرێ","هەویرترش","توێکڵ","کولێچە","شیرینخانە"],
    bluff:["نانەوایی","نان","کێک","شیرینی","خۆش","بەیانی","نانپەزی","هەویر","کولێچە","ئارد"] },

  { secret:"ئاگرکێو", hint:"چیا",
    obvious:["لاڤا","تەقینەوە","ماگما","دەمار","خۆڵەمێش","دووکەڵ","دوورگە","گەرمی","دەنگی مۆتەکە","لووتکە"],
    medium:["هەڵکشان","بەرد","بەرز","هەور","قەدەغە","دیمەن","لووتکە","ڕێگا","ئاگر","بەرد"],
    subtle:["خەوتوو","سوور","گوشار","ئاگاداری","دێرین","قووڵ","مۆتەکە","کەلێنی زەوی","تەقینەوە","تواوە"],
    bluff:["ئاگرکێو","چیا","ئاگر","تەقینەوە","لاڤا","خۆڵەمێش","دووکەڵ","لووتکە","دەمار","بەرد"] },

  { secret:"شوالیێ", hint:"قەڵا",
    obvious:["شمشێر","زرێ","قەڵغان","ڕمی درێژ","ئەسپ","پاڵەوانی","پاشا","شاژن","شەڕ","هێرشکردن"],
    medium:["ڕێز","دڵسۆزی","ئەرک","کۆیلە","ڕاهێنان","شەڕ","دوژمن","دیلگرتن","قوللە","ئاڵا"],
    subtle:["گەمارۆ","تاج","قەڵا","بەجگر","شوالیێ","ئەسپ","شەڕی تاک","پاسەوان","سوێند","بەرد"],
    bluff:["شوالیێ","قەڵا","شەڕ","زرێ","قەڵغان","شمشێر","پاشا","شاژن","ئەسپ","جەنگ"] },

  { secret:"جادوگەر", hint:"مەنجەڵ",
    obvious:["گۆچانی گەشتیاری","دەرمانی جادویی","کتێبی نهێنی","تۆپی کریستاڵ","لێدان","مۆم","وشەی نهێنی","کەڵبەی ماڵ","گیایی","مانگ"],
    medium:["بازنە","نیشانە","جادو","نەفرەت","تاریک","فڕین","دارستان","قەلەڕەش","کەوا","ئاوێنە"],
    subtle:["پچڕپچڕ","سێبەر","ڕۆح","نهێنی","جادوگەری","دەرمانی جادویی","کۆمەڵ","سیحرکردن","تەم","ئەستێرە"],
    bluff:["جادوگەر","جادو","سیحر","دەرمانی جادویی","مەنجەڵ","کریستاڵ","مانگ","دارستان","تاریک","قەلەڕەش"] },

  { secret:"بۆشایی", hint:"ئەستێرەکان",
    obvious:["فەزاوان","ڕاکێت","تەلەسکۆپ","سەیارەی چاودێری","هەسارە","ئەستێرە","خولگە","مانگ","گەلاکسی","بۆشایی"],
    medium:["ساڵی ڕووناکی","بێدەنگی","کێشی زەوی","گەشتکردن","بێگانە","ئەستێرەی کاول","بۆشایی","قووڵ","بەرزبوونەوە","هەورەستێرە"],
    subtle:["خۆری","خۆر","گەشت","بێکێشی","بۆشاییانە","تاریکی","گەردوون","ئەستێرەناسی","ئەرک","ئەندام"],
    bluff:["بۆشایی","ڕاکێت","ئەستێرە","هەسارە","فەزاوان","گەلاکسی","خولگە","مانگ","خۆر","گەشتکردن"] },

  { secret:"دارستانی گەرمسێر", hint:"کێوی",
    obvious:["پڵنگ","تۆتی","مار","شەلاڵە","سەربان","مەیموون","کەوڵ","ورد","ڕووبار","سەوز"],
    medium:["شێی","دەزوو","حەشیمەت","تەم","سرخس","سەرکێشی","بوونەوەر","چڕ","خاک","باران"],
    subtle:["سێبەر","دەنگ","ئەشکەوت","کێوی","قووڵ","نامۆ","خۆرتاو","دارستان","گەشت","کێوی"],
    bluff:["دارستان","دارستانی گەرمسێر","پڵنگ","تۆتی","ڕووبار","سەربان","مەیموون","سەوز","کێوی","سەرکێشی"] },

  { secret:"شەبح", hint:"ڕۆح",
    obvious:["ڕۆحی گمژاو","خەیاڵ","ئێکتۆپلازم","ناوبژیوان","ماڵی شەیتانی","پچڕپچڕ","سێبەر","خاڵی سارد","زنجیر","ترس"],
    medium:["هەنگاو","بیرەوەری","سارد بوونی لەناکاو","تەواونەکراو","تروسکە","مردوو","هاوار","تاریکی","دەنگی دار","ماڵی کۆن"],
    subtle:["ترسناک","تۆقین","بۆشایی","گۆڕ","ڕۆح","بینین","نادیار","ترساندن","دەنگدانەوە","گیان"],
    bluff:["شەبح","ماڵی شەیتانی","ڕۆح","خەیاڵ","تاریکی","ترس","هاوار","ماڵی کۆن","سێبەر","پچڕپچڕ"] },

  { secret:"قومارخانە", hint:"مەترسیدار",
    obvious:["ڕولێت","خەڵاتی گەورە","پۆکەر","بلاکجاک","ژیتۆن","زاری","کارت","گرەو","بژاردەی بەرز","دابەشکەر"],
    medium:["بەخت","درۆکردن","دڵەڕاوکێ","سیستەم","نیشانە","مەترسی","براوە","دۆڕاو","پارە","یاری"],
    subtle:["نۆرە","چاودێری","بێدەنگی","گوشار","ستراتیژی","قومار","بژاردە","درۆکردن","قوماشی سەوز","قومارخانە"],
    bluff:["قومارخانە","پۆکەر","ڕولێت","زاری","ژیتۆن","گرەو","بەخت","دابەشکەر","براوە","پارە"] },

  { secret:"شانۆ", hint:"سەکۆ",
    obvious:["تیشکی سەکۆ","بانگی کۆتایی","وتاری تاک","چەپڵەڕێزان","دەقی شانۆیی","جلوبەرگ","پشتی سەکۆ","خۆشدەستکردن","ڕازاندنەوە","ئەکتەر"],
    medium:["هەست","کاتبەندی","هەناسە","ماسک","دەستکاریکردن","ئەکتەری","سەکۆ","ڕۆڵ","دیمەن","دەرچوون"],
    subtle:["پێشاندان","خەڵک","ڕووناکی","دەنگ","ئاوێنە","دراما","بینەر","کەسایەتی","گفتوگۆ","یاری"],
    bluff:["شانۆ","سەکۆ","ئەکتەر","دەقی شانۆیی","پەردە","چەپڵەڕێزان","پێشاندان","ڕووناکی","ڕۆڵ","یاری"] },

  { secret:"مازە", hint:"لابیرینت",
    obvious:["مینۆتۆر","کۆتایی داخراو","لابیرینت","دەزوو","خواردنەوە","سوڕان","پەرژین","ناوەڕاست","مامناوە","ئاوێنە"],
    medium:["هەڵبژاردن","دەنگدانەوە","ڕێگا","چارەسەر","ڕێچکە","کونج","تاریک","با","سەرلێشێواوی","بەرد"],
    subtle:["دەرچوون","قەفەز","ڕاونان","تەڵە","داخراو","مازە","چەمانەوە","مارپێچ","شکاندن","ون بوو"],
    bluff:["مازە","لابیرینت","ڕێچکە","سوڕان","دیوار","کۆتایی داخراو","سەرلێشێواوی","چەمانەوە","ون بوو","مامناوە"] },

  { secret:"قوتابخانە", hint:"پۆل",
    obvious:["تەختەی ڕەش","کتێبی دەرسی","مامۆستا","تاقیکردنەوە","وانە","خوێندکار","مێز","زەنگ","نمرە","ئەرکی ماڵەوە"],
    medium:["فێربوون","زانیاری","بابەت","بیرکاری","زانست","مێژوو","خوێندنەوە","نووسین","خوێندن","پۆل"],
    subtle:["هاوڕێ","یاریگا","دواکەوتن","دواهاتن","کتێبخانە","تیشکخستنە سەر","کنجاوی","قوتابخانە","دەفتەر","پێنووس"],
    bluff:["قوتابخانە","مامۆستا","خوێندکار","پۆل","وانە","تاقیکردنەوە","فێربوون","نمرە","مێز","ئەرکی ماڵەوە"] },

  { secret:"دارستان", hint:"بیشە",
    obvious:["بەڕوو","سنەوبەر","کەوڵ","جۆگە","ئاسک","گورگ","دار","سەربان","قارچ","ڕێچکە"],
    medium:["سەوز","ئارام","سێبەر","بێدەنگی","خاک","کێوی","کەمپ","گەشتی پیاسە","پەناگا","سروشت"],
    subtle:["گوێگرتن","نەجوڵان","ڕووناکی","سێبەر","دارستان","تەنیایی","ئاژەڵ","دار","جێگای خەو","سرخس"],
    bluff:["دارستان","دار","سەوز","ئاسک","گورگ","ڕێچکە","کەمپ","گەشتی پیاسە","سروشت","ئارام"] },

  { secret:"قەڵا", hint:"پاشایەتی",
    obvious:["پاشا","شاژن","تەخت","زرێ","تاج","شوالیێ","چۆم","پردی هەڵکێشراو","قوللە","پاشایەتی"],
    medium:["شاهانە","دادگا","گەمارۆ","ئاڵا","بەرد","تالار","پاسەوان","مەسخەرەباز","خوان","شەڕ"],
    subtle:["دەسەڵات","مێژوو","دێرین","میرات","قەڵا","پاراستن","بەرزی","ڕێگای نهێنی","میراتگر","کۆشک"],
    bluff:["قەڵا","پاشا","شاژن","شوالیێ","تاج","تەخت","زرێ","چۆم","شاهانە","قوللە"] },

  { secret:"ئۆقیانوس", hint:"دەریا",
    obvious:["شەپۆل","مەد و جەزر","مەرجان","کوسە","دۆلفین","ولحوت","بادبان","قووڵ","کەنار","بۆقاڵچین"],
    medium:["شین","خوێ","با","ئاسۆ","گەشت","دوورگە","ڕیف","جۆشی ئاو","دەریایی","ئاو"],
    subtle:["ئازادی","فراوان","ئارام","ڕەشەبا","دەریا","دەریاوان","هێمن","قووڵایی","مۆج","دەریایی"],
    bluff:["دەریا","ئۆقیانوس","شەپۆل","مەد و جەزر","کوسە","دۆلفین","بادبان","قووڵ","شین","کەنار"] },

  { secret:"چیا", hint:"لووتکە",
    obvious:["لووتکە","بەفر","کەنداڵ","هەڵکشان","بەرد","هەور","لێواری","بەرز","دیمەن","سەرکەوتن"],
    medium:["هەڵکشان","سارد","با","بەرزی","ڕێچکە","بەرد","بێدەنگی","لووتکە","سەرکێشی","بەردی گرانیت"],
    subtle:["سەرەوە","نەجوڵان","چیا","کێوی","هەوا","شکۆمەندی","لووتکە","ئاست","لێوار","سەرکەوتن"],
    bluff:["چیا","لووتکە","بەفر","هەڵکشان","بەرد","سەرکەوتن","کەنداڵ","دیمەن","سارد","بەرزی"] },

  { secret:"کێڵگە", hint:"گوند",
    obvious:["تراکتۆر","ئەمبار","مانگا","دروێنە","گەنم","گیسان","مریشک","ئەسپ","کا","کێڵگە"],
    medium:["خۆرهەڵاتن","خاک","سێو","باخی میوە","گوند","دانەوێڵە","ئەمباری زەخیرە","ماڵی جوتیار","حەوش","دەروبار"],
    subtle:["بێدەنگی","نان","خاک","سادە","گوند","کا","لەوەڕگا","ئەمبار","سەوزە","کێڵگە"],
    bluff:["کێڵگە","ئەمبار","مانگا","تراکتۆر","دروێنە","گەنم","ئەسپ","دەروبار","مریشک","کا"] },

  { secret:"شەمەندەفەر", hint:"ڕێگای ئاسن",
    obvious:["ماشینی تڕەن","ڤاگۆن","وێستگە","ڕێڵ","بەڕێوەبەری تڕەن","هەڵم","فیشکە","سەکۆ","ڕۆیشتن","گەیشتن"],
    medium:["گەشتیار","ڕێچکە","گەشت","نیشانە","بار","خێرا","ڕێڵ","گەشتکردن","بلیت","کات"],
    subtle:["پەنجەرە","دیمەن","دووری","شەو","تڕەن","ڕێگای ئاسن","تێپەڕین","وێستگە","کاتبەندی","کورسی"],
    bluff:["تڕەن","شەمەندەفەر","وێستگە","ڕێڵ","بەڕێوەبەری تڕەن","هەڵم","گەشت","بلیت","گەشتیار","فیشکە"] },

  { secret:"فڕۆکەخانە", hint:"فڕین",
    obvious:["فڕۆکە","فڕۆکەوان","ڕێگای فڕین","سواربوون","تێرمینال","بەرزبوونەوە","دابەزین","بارگە","پاسپۆرت","دەروازە"],
    medium:["فڕین","گەشتکردن","مەقصەد","پاسەوانی","ڕۆیشتن","گەیشتن","کۆمپانیای فڕۆکەوانی","ژووری فەرمانی","قوللەی چاودێری","ئاسمان"],
    subtle:["پەیوەندی","دواکەوتن","کارتی سواربوون","سەرەوە","تاکسیکردن","فڕۆکەخانە","بەرزبوونەوە","گەشتیار","بەرنامەی گەشت","ڕێگای فڕین"],
    bluff:["فڕۆکەخانە","فڕۆکە","فڕۆکەوان","فڕین","ڕێگای فڕین","سواربوون","گەشتکردن","تێرمینال","دابەزین","دەروازە"] },

  { secret:"کەرناڤاڵ", hint:"کامەرانی",
    obvious:["چەرخی گەورە","هێلانەی خێرا","بەفری شیرین","کارۆسێل","یاری","خەڵات","بلیت","سواری","مەسخەرەباز","هاوار"],
    medium:["ڕووناکی","مۆسیقا","خەڵک","پێکەنین","خۆشی","کەرناڤاڵ","چادر","سەرسوڕمان","کامەرانی","سواری"],
    subtle:["خۆشی","بیرەوەری","سووڕان","تروسکە","کەرناڤاڵ","خۆرئاوابوون","ئاهەنگ","شیرینی","سەرسوڕمان","سووڕانەوە"],
    bluff:["کەرناڤاڵ","کامەرانی","سواری","یاری","بلیت","بەفری شیرین","چەرخی گەورە","هێلانەی خێرا","خەڵات","خەڵک"] },

  { secret:"قەڵا", hint:"پاشایەتی",
    obvious:["پاشا","شاژن","تەخت","زرێ","تاج","شوالیێ","چۆم","پردی هەڵکێشراو","قوللە","پاشایەتی"],
    medium:["شاهانە","دادگا","گەمارۆ","ئاڵا","بەرد","تالار","پاسەوان","مەسخەرەباز","خوان","شەڕ"],
    subtle:["دەسەڵات","مێژوو","دێرین","میرات","قەڵا","پاراستن","بەرزی","ڕێگای نهێنی","میراتگر","کۆشک"],
    bluff:["قەڵا","پاشا","شاژن","شوالیێ","تاج","تەخت","زرێ","چۆم","شاهانە","قوللە"] },

  { secret:"کەناراو", hint:"کەنار",
    obvious:["ڕیگ","خۆر","شەپۆل","بۆقاڵچین","هاولە","عەینەکی خۆر","بروونبوونی پێست","مەلەکردن","قەڵای ڕیگ","مۆجسواری"],
    medium:["خوێ","شنەبا","هاوین","حەوانەوە","کەنار","کەناراو","کەنار","مەد و جەزر","پشوو","دەریا"],
    subtle:["ئاسۆ","ئارام","قەڵای ڕیگ","خۆرئاوابوون","کەناراو","خۆشی","گردۆنە","پیاسە","ئاشتی","کەنار"],
    bluff:["کەناراو","ڕیگ","خۆر","شەپۆل","بۆقاڵچین","هاولە","مەلەکردن","قەڵا","مۆجسواری","دەریا"] },

  { secret:"ئەشکەوت", hint:"ژێرزەوی",
    obvious:["بەردی هەڵواسراو","بەردی ڕاوەستاو","تاریکی","دەنگدانەوە","شەمشەمەڵک","کریستاڵ","دالان","ژوور","ئەشکەوتی گەورە","ژێرزەوی"],
    medium:["گەڕان","بێدەنگی","دڵۆپ","بەرد","سەرکێشی","ئەشکەوت","شاراوە","گەنجینە","سێبەر","ژێرزەوی"],
    subtle:["نهێنی","سارد","تەڕ","دێرین","پەناگا","ئەشکەوت","خاک","بۆشایی","دەنگدانەوە","کۆن"],
    bluff:["ئەشکەوت","ژێرزەوی","تاریک","بەرد","بەردی هەڵواسراو","ئەشکەوتی گەورە","شەمشەمەڵک","دەنگدانەوە","سەرکێشی","شاراوە"] },

  { secret:"خەیمەهەڵدان", hint:"دەرەوە",
    obvious:["چادر","ئاگری کەمپ","جانتای خەو","پیاسە","مارشمیلۆ","ڕێچکە","کێوی","ئەستێرەکان","دارستان","سروشت"],
    medium:["ڕووناکی","دەنگی سووتان","برژان","سەرکێشی","دەرەوە","کەمپ","گۆل","چیا","بێدەنگی","مێرگ"],
    subtle:["بۆن","ئاشتی","ئاسمان","کەمپکردن","دەرباز بوون","تەنیایی","سنەوبەر","خەڵووزی سووتاو","سادە","کەمپ"],
    bluff:["کەمپکردن","چادر","ئاگری کەمپ","پیاسە","ڕێچکە","مارشمیلۆ","ئەستێرەکان","دارستان","سروشت","دەرەوە"] },

  { secret:"باخچە", hint:"شکوفە",
    obvious:["وەرد","لاڵە","بابونە","گوڵی خۆر","باخچە","گوڵبەند","گەڵای گوڵ","خاک","شکوفە","پەرژین"],
    medium:["سەوز","ڕووەک","ئاو","گەشەکردن","لێدان","باخچە","پەپولە","هەنگ","بۆنی خۆش","سروشت"],
    subtle:["ئاشتی","تۆزی گوڵ","باخچە","شەونم","بەیانی","ساڵانە","گەڵا","خۆشەویستی","شکوفە","لق"],
    bluff:["باخچە","گوڵ","وەرد","لاڵە","شکوفە","ڕووەک","سەوز","خاک","گوڵی خۆر","گەڵا"] },

  { secret:"میوانخانە", hint:"میخانە",
    obvious:["میخانە","بیرە","ئۆجاق","خاوەنی میوانخانە","ژوور","ژووری گشتی","سەردابە","چێشتخانە","میوان","ئاژووش"],
    medium:["گەرمی","کۆبوونەوە","گەشتیار","میوانداری","میوانخانە","ئاگر","نیمکە","مانەوەگا","دەشتودەر","کۆن"],
    subtle:["ئارامی","بێدەنگی","دەرباز بوون","گوند","میوانخانە","سەربان","شەو","چیرۆک","خۆشی","ئاگری گڕان"],
    bluff:["میوانخانە","میخانە","بیرە","ئۆجاق","میوان","ئاگر","ژوور","خاوەنی میخانە","گەشتیار","خۆشی"] },

  { secret:"کیمیاگەر", hint:"تاقیگە",
    obvious:["ئێلیکسیر","کریستاڵ","بتڵکە","سووتاندن","ئاگر","شووشە","کیمیا","مێزی کار","خەڵووز","دەرمانی گیانبەخش"],
    medium:["فلاسک","تۆز","خەڵووز","کوڵان","کیمیاگەر","کاڵا","مۆعجزەگەری","ڕەف","خوێندنەوە","دانایی"],
    subtle:["ڕێسەت","هاوسەنگی","ڕوون","کیمیاگەر","قوتابی","بتڵکەی بچووک","کاریگەر","دروستکردن","گۆڕان","کانزا"],
    bluff:["کیمیاگەر","ئێلیکسیر","کریستاڵ","بتڵکە","کوڵان","ئاگر","شووشە","تاقیگە","کیمیا","دەرمانی گیانبەخش"] },

  { secret:"کڵیسای گەورە", hint:"پیرۆز",
    obvious:["شووشەی ڕەنگاوڕەنگ","ئۆرگ","دانپێدانان","کورسی کڵیسا","زەنگ","قوربانگا","تاقی","مێزی خوێندن","بخوور","سروود"],
    medium:["بەرد","تاقی بەرزکراوە","پیرۆز","مۆسیقای ئایینی","کڵیسای گەورە","شێوازی گۆتیک","چۆکدانان","گوڵ","وتاری ئایینی","ئارامی"],
    subtle:["بێدەنگی","تروسکە","بخوور","کڵیسای گەورە","تاقی","شکۆمەندی","ڕووناکی","خواپەرستی","پەرستگا","قوللە"],
    bluff:["کڵیسا","کڵیسای گەورە","شووشەی ڕەنگاوڕەنگ","ئۆرگ","زەنگ","قوربانگا","کورسی کڵیسا","بەرد","پیرۆز","سروود"] },

  { secret:"ستۆدیۆ", hint:"هونەر",
    obvious:["قوماشی وێنە","فرچە","ڕەنگ","مۆلبێت","پالێت","سکێچ","تین","پەیکەرتاشی","شاکار","ستۆدیۆ"],
    medium:["ڕەنگ","ڕووناکی","پێکهاتە","دروستکردن","هونەرمەند","قوماشی وێنە","پێشانگا","مۆزەخانە","گالەری","ئیلهام"],
    subtle:["تایبەت","خەیاڵ","ستۆدیۆ","قوماشی بەتاڵ","شێواز","تێکستچەر","بینین","چوارچێوە","ڕازاندنەوە","کەموکوڕی"],
    bluff:["ستۆدیۆ","هونەر","قوماشی وێنە","فرچە","ڕەنگ","مۆلبێت","پالێت","پەیکەرتاشی","ڕەنگ","هونەرمەند"] },

  { secret:"میخانە", hint:"خواردنەوە",
    obvious:["بار","کوپ","بیرە","خاوەنی میخانە","کورسی","میخانە","کەشک","تانکارد","تاپ","سەردابە"],
    medium:["گەرمی","ئاگر","پێکەنین","گۆرانی","زاری","کارت","دەمامک","میخانە","میوان","پارێزگار"],
    subtle:["کۆمپانیای باش","تروسکە","کۆن","میخانە","بەردەم بار","بێدەنگی","بتڵ","گەشت","چیرۆک","کوپ"],
    bluff:["میخانە","بار","بیرە","کوپ","خاوەنی میخانە","ئاگر","کەشک","گۆرانی","کارت","میوان"] },

  { secret:"زیندانی ژێرزەوی", hint:"تاریک",
    obvious:["زنجیر","خانە","ئەشکەنجە","بەندکراو","سەرپەرشتیار","تاریکی","مشک","زیندانی ژێرزەوی","ئامێری ئەشکەنجە","زیندان"],
    medium:["تەڕ","بەرد","پاسەوان","ئاسن","هەڵاتن","تەنیایی","زیندانی ژێرزەوی","کونجی لەبیرکراو","دالان","مەشقە"],
    subtle:["بێدەنگی","دەنگدانەوە","تۆڕی جاڵجاڵۆکە","بێهیوایی","زیندانی ژێرزەوی","بێڕووناکی","دالان","لەبیرکراو","ناڵین","کونج"],
    bluff:["زیندان","زیندانی ژێرزەوی","خانە","زنجیر","سەرپەرشتیار","مشک","تاریکی","بەرد","پاسەوان","هەڵاتن"] },

  { secret:"کۆشک", hint:"کۆن",
    obvious:["تالاری سەما","چڵچرا","پێپلیکانەی مارپێچ","ژووری میوان","خزمەتکار","هۆڵ","ژووری خوێندنەوە","کریستاڵ","کۆشک","وێنەی کەسێک"],
    medium:["موڵک","پەردەی نەخشدار","عەتیقە","کتێبخانە","زیو","پەرژین","کۆشک","باخچە","مەزن","ڕازاوەیی"],
    subtle:["تۆز","دەرگای نهێنی","دەنگدانەوە","سێبەر","کۆشک","بەجێهێڵراو","کریسک","تاقی بەرزکراوە","سامان","بەفیڕۆدراو"],
    bluff:["کۆشک","کۆن","موڵک","تالاری سەما","چڵچرا","خزمەتکار","ژووری خوێندنەوە","باخچە","مەزن","کریستاڵ"] },

  { secret:"فەوارە", hint:"ئاو",
    obvious:["خۆفڕێدان","حەوزە","پەیکەر","دەنگی ئاو","حەوشە","ئاواتی","دراو","کەوڵ","فەوارە","پەیکەرتاشی"],
    medium:["ڕژان","ڕوون","سارد","فەوارە","گۆڕەپان","تایبەتمەندی","بڕۆنز","مەڕمەڕ","سپرین","حەوزە"],
    subtle:["شەو","ڕەنگدانەوە","فەوارە","ئارام","بۆشایی","بەرد","تیشکی خۆر","دڵۆپ","باخچە","ئاشتی"],
    bluff:["فەوارە","ئاو","حەوزە","پەیکەر","دراو","ئاواتی","ڕژان","حەوشە","بڕۆنز","مەڕمەڕ"] },

  { secret:"قوللەی کاتژمێر", hint:"کات",
    obvious:["زەنگ","میکانیزم","ڕووی کاتژمێر","فەنەر","چەرخدەندان","قوللە","سەعات","دەنگی زەنگ","کات","ڕەقاس"],
    medium:["لێدان","خۆرئاوابوون","خۆرهەڵاتن","کاتژمێر","مەزن","دەنگی چەرخ","قوللە","جێگیر","سێبەر","میکانیزم"],
    subtle:["زەنگارگرتن","تیک","تاک","چاوەڕوانی","قوللە","ساتێک","بێکۆتایی","دێرین","پیشەسازی","شۆڕش"],
    bluff:["قوللەی کاتژمێر","کات","زەنگ","چەرخدەندان","ڕووی کاتژمێر","دەنگی زەنگ","قوللە","سەعات","ڕەقاس","میکانیزم"] },

  { secret:"کەنارگە", hint:"بەندەر",
    obvious:["کەنداو","دەمرگای کەشتی","قەراغی بەرز","بەلەم","بەلەمی بچووک","بادبان","کەشتی","دیمانکردن","کەنارگە","ئەشکەوتی بچووک"],
    medium:["پەناگا","مەد و جەزر","خۆڵ","کەنارگە","بەندەر","دوورگە","بادبان","سەکۆ","ئارام","کەنار"],
    subtle:["تایبەتمەندی","کەنارگە","ڕۆیشتن","کەنار","بەرد","شاراوە","گۆلی کەنداوی","ئەشکەوتی بچووک","بێدەنگی","دەروازە"],
    bluff:["کەنارگە","بەندەر","کەنداو","بەلەم","کەشتی","بادبان","قەراغی بەرز","دوورگە","دیمانکردن","کەنار"] },

  { secret:"مێرگ", hint:"کێڵگە",
    obvious:["گژوگیا","گوڵی کێوی","جۆگە","پەپولە","لەوەڕان","مێرگ","شنەبا","گژوگیای سێگەڵا","خۆرتاو","مانگا لەوەڕاو"],
    medium:["سەوز","چیا","مانگا","مەڕ","شکوفە","مێرگ","گوڵ","تەڕوتازە","بابونە","کوندەڵی هەنگ"],
    subtle:["ئارام","مێرگ","کا","بۆن","تەنیایی","کاتی زێڕین","لەوەڕان","بێدەنگی","شیرەی گوڵ","نەرم"],
    bluff:["مێرگ","کێڵگە","گژوگیا","گوڵی کێوی","جۆگە","پەپولە","گردۆنە","شنەبا","لەوەڕان","سەوز"] },

  { secret:"گۆڕستانی ژێرزەوی", hint:"گۆڕ",
    obvious:["ئێسکەڵ","دالان","تابووتی بەردین","کونجی دیوار","چرا","ژێرزەوی گۆڕستان","ئێسک","گۆڕستانی ژێرزەوی","ژوور","تۆز"],
    medium:["تاریک","دەنگدانەوە","ڕێگا","بەرد","لەبیرکراو","هێڵکراو","گۆڕستانی ژێرزەوی","تاقی","کۆڵەکە","دالان"],
    subtle:["بێدەنگی","گۆڕستانی ژێرزەوی","وێنەی دیواری","ڕۆح","ون بوو","نووسینی سەر گۆڕ","مۆم","هەوا","لابیرینت","کۆن"],
    bluff:["گۆڕستانی ژێرزەوی","گۆڕ","ژێرزەوی گۆڕستان","ئێسکەڵ","تونێل","ئێسک","ژوور","تاریک","بەرد","لەبیرکراو"] },

  { secret:"ئەستوورلاب", hint:"ئەستێرەکان",
    obvious:["ئەستوورلاب","کۆمەڵەئەستێرە","ئەستێرەی باکوور","سێکستانت","ئاسمانی","هەسارە","ئەستێرە","تەلەسکۆپ","نیشانگر","خشتە"],
    medium:["کورە","ئامێری ئاسمانناسی","نەخشە","ڕێنیشاندان","ئەستوورلاب","زانست","بڕۆنز","کۆن","خوێندەوار","چاودێریکردن"],
    subtle:["وردەکاری","سەرسوڕمان","ئەستوورلاب","ئاسمان","خولانەوە","ئەستێرەناسی","کۆن","خشتەی ئەستێرە","ئامێر","گەشتکردن"],
    bluff:["ئەستوورلاب","ئەستێرەکان","نەخشە","ڕێنیشاندان","هەسارە","تەلەسکۆپ","ئاسمانی","خشتە","کۆمەڵەئەستێرە","کۆن"] },

  { secret:"گەمارۆ", hint:"شەڕ",
    obvious:["مەنجەنیق","بەرقاچی شکاندنی دەروازە","دیوار","شەڕ","ترێبۆشێت","تیر","بەربەست","هێرش","قوللە","گەمارۆ"],
    medium:["کەمپ","ئاڵا","قەڵا","گەمارۆ","دەوردان","تێکشکان","بەرد","ورەی جەنگ","ئامێر","دیوار"],
    subtle:["ڕاوەستان","دڵەڕاوکێ","گەمارۆ","تۆز","پاشکەوت","ئاڵا","کەڕەنا","ئاسوودەیی","زرێ","هێرش"],
    bluff:["گەمارۆ","شەڕ","مەنجەنیق","قەڵا","تیر","قوللە","دیوار","کەمپ","ئاڵا","هێرش"] },

  { secret:"پارچمێن", hint:"تۆمار",
    obvious:["پەڕی نووسین","مرەکەب","تۆمار","مۆر","دەستنووس","پێستی نووسین","نامە","تیپی هێڵکراو","پارچمێن","کاغەز"],
    medium:["کاغەز","بەڵگەنامە","مێژوو","پارچمێن","کتێبخانە","کۆنینە","واژۆ","نووسەرەوە","کتێب","تۆمار"],
    subtle:["ناسک","زەردبوو","پارچمێن","دەست","کۆن","تۆمار","تیپی هێڵکراو","پێستی مانگا","نامە","ئەرشیف"],
    bluff:["پارچمێن","تۆمار","پەڕی نووسین","مرەکەب","نامە","مۆر","دەستنووس","پێستی نووسین","بەڵگەنامە","کۆن"] },

  { secret:"کوورە", hint:"ئاگر",
    obvious:["سندان","چەکوش","مووشتە","ئاسن","بریسکە","تیغ","مەنقاش","کوورە","کانزا","لێدان"],
    medium:["ئاگر","تروسکە","دووکەڵ","لێدان","دەنگی زەنگ","کوورە","چەکوشکاری","چەک","زرێ","گەرمی"],
    subtle:["فیشکە","خەڵووز","ئاهەنگ","تیلی ئاسن","کوورە","کار","پیشە","کانزای خاو","دەنگی چەکوش","شارەزایی"],
    bluff:["کوورە","ئاگر","سندان","چەکوش","ئاسن","تیغ","چەکوشکاری","گەرمی","بریسکە","چەک"] },

  { secret:"گۆڕ", hint:"ناشتن",
    obvious:["تابووتی بەردین","ئەهرام","فیرعەون","هێرۆگلیف","گۆزەی مۆمیایی","گۆڕ","بەرد","ژوور","ماسک","موسکە"],
    medium:["ژێرزەوی گۆڕستان","نیشانە","گەنجینە","گۆڕ","مۆمیا","شکاو","ملیم","پاسەوان","ڕۆح","کاهین"],
    subtle:["هەتاهەتایی","تاریکی","گۆڕ","حەوانەوە","دەنگدانەوە","پارێزراو","ئەبولهەول","لم","دەروازە","واحە"],
    bluff:["گۆڕ","ناشتن","ئەهرام","فیرعەون","تابووتی بەردین","هێرۆگلیف","مۆمیا","ژێرزەوی گۆڕستان","بەرد","ماسک"] },

  { secret:"پەرستگا", hint:"پیرۆز",
    obvious:["پەرستگا","دەروازەی پەرستگا","قوربانی","فاڵگرتنەوە","چرا","کڕنووش","ڕاهیب","بخوور","پیرۆزگا","لادەن"],
    medium:["ئاشتی","نوێژ","گوریس","پچڕپچڕ","پەرستگا","پارێزەر","پیرۆز","هەڵکشان","دار","دەروازە"],
    subtle:["بەجدییەوە","پەرستگا","ڕووناکی","بێجوڵەیی","سوێند","شکوفە","هەنگاو","دەنگی زەنگ","ڕۆح","سنوور"],
    bluff:["پەرستگا","پیرۆز","بەرد","قوربانی","دەروازەی پەرستگا","چرا","نوێژ","ڕاهیب","بخوور","ئاشتی"] },

  { secret:"چۆمی قەڵا", hint:"ئاو",
    obvious:["پردی هەڵکێشراو","چۆمی قەڵا","ئاو","بەرگری","قەڵا","دەروازە","ڕەنگدانەوە","تیمساح","بێجوڵە","دیوار"],
    medium:["تەڕ","قووڵ","بەربەست","ڕەنگدانەوە","چۆمی قەڵا","تاریک","بەرد","ماسی","لاڵە","لێوار"],
    subtle:["بێدەنگی","چۆمی قەڵا","تەڵە","سێبەر","کۆن","بێجوڵە","بەرد","بەجێهێڵراو","دەنگدانەوە","سارد"],
    bluff:["چۆمی قەڵا","ئاو","پردی هەڵکێشراو","قەڵا","بەرگری","دەروازە","دیوار","تەڕ","قووڵ","تیمساح"] },

  { secret:"ژێرزەوی گۆڕستان", hint:"زیندان",
    obvious:["تابووت","ئێسک","ئێسکەڵ","قوربانگا","مۆم","تۆز","تۆڕی جاڵجاڵۆکە","کێلی گۆڕ","کاسەسەر","ژێرزەوی گۆڕستان"],
    medium:["کەفەن","ژوور","مۆم","تاریک","ژێرزەوی گۆڕستان","دەنگدانەوە","تاقی","بەرد","بەردی هەڵواسراو","تابووتی بەردین"],
    subtle:["بێدەنگی","دێرین","ژێرزەوی گۆڕستان","لەبیرکراو","سارد","نوێژ","شەبح","خەمۆکی","بیرەوەری","پیرۆزگا"],
    bluff:["ژێرزەوی گۆڕستان","زیندان","تابووت","ئێسک","ئێسکەڵ","قوربانگا","تۆز","کاسەسەر","مۆم","تاریک"] },

  { secret:"کتێبخانە", hint:"کتێب",
    obvious:["ڕەف","بەرگی گەورە","کتێب","کتێبخانەوان","پێرست","چرا","خوێندنەوە","ئەرشیف","تۆز","کارت"],
    medium:["خوێندن","گلۆب","بێدەنگی","کتێب","سامان","زانیاری","لاپەڕە","نامە","مێژوو","خۆشەویستی کتێب"],
    subtle:["بێدەنگی","کتێب","فێربوون","کۆن","بەستنەوە","مرەکەب","کاغەز","کەسایەتی","کلاسیک","دانایی"],
    bluff:["کتێبخانە","کتێب","ڕەف","خوێندنەوە","بەرگی گەورە","کتێبخانەوان","پێرست","چرا","خوێندن","زانیاری"] },

  { secret:"ئۆبزەرڤاتۆری", hint:"ئاسمان",
    obvious:["تەلەسکۆپ","گومبەز","هەسارە","ئەستێرە","ئەستێرەناس","ئۆبزەرڤاتۆری","خولگە","هەورەستێرە","خشتە","گومبەزی بچووک"],
    medium:["شەو","کۆمەڵەئەستێرە","ئۆبزەرڤاتۆری","ئامێر","زیو","تیشکبڕی","ئاوێنە","مانگ","خۆری","دوربین"],
    subtle:["ئاسمان","تەنیایی","ئۆبزەرڤاتۆری","ڕووناکی","سەرسوڕمان","تاریک","گیرگۆشە","سەربان","زانست","گەردوون"],
    bluff:["ئۆبزەرڤاتۆری","تەلەسکۆپ","ئەستێرەکان","هەسارە","گومبەز","ئەستێرەناس","خولگە","مانگ","شەو","ئاسمان"] }
];

export const DECK = { en: DECK_EN, ku: DECK_KU };

export const NPCS = [
  { id:"brute", name:"Gruff Halloran", name_ku:"گراف هاڵۆران", chip:"#b98a4f", aggression:0.8, caution:0.25, tell:0.25,
    thinkMs:[900,1700] },
  { id:"widow", name:"Madame Vey",     name_ku:"مادام ڤێی",   chip:"#9c6b7c", aggression:0.35, caution:0.75, tell:0.12,
    thinkMs:[1600,2600] },
  { id:"fox",  name:"Silky Marlowe",   name_ku:"سیلکی مارلۆ",  chip:"#8fa06b", aggression:0.55, caution:0.5,  tell:0.4,
    thinkMs:[700,1400] },
];

export const RULES = {
  seats: 4,
  maxRounds: 4,
  voteUnlockRound: 2,
  handSize: 4,
  weights: { obvious:3, medium:2, subtle:1 },
};
