// The Deception Table — all player-visible strings live here.
// Swapping language = swapping this file's contents.
export const STR = {
  title_blurb: "Three of you share a secret word. One of you only has a hint. Say a word each round — subtle enough to hide the secret, clear enough to prove you know it. Then vote. The revolver settles the rest.",
  start: "Deal the Cards",
  play_again: "Deal Again",
  loading: "Lighting the lantern…",
  round_tag: "Round {r} of {max}",
  vote_tag: "The Vote",
  your_card_label: "Your card",
  imposter_card: "IMPOSTER",
  imposter_hint: "hint: {h}",
  hold_to_peek: "Hold to peek at your card",
  prompt_your_turn: "Your turn. Choose your word carefully…",
  prompt_waiting: "{n} is thinking…",
  prompt_vote: "Who is the imposter? Cast your vote.",
  prompt_revote: "The chamber was empty. One more round — then vote again.",
  call_vote: "Call the Vote",
  tier_obvious: "bold",
  tier_medium: "steady",
  tier_subtle: "sly",
  tier_bluff: "bluff",
  said: "{w}",
  banner_tie: "DEAD EVEN — THE CHAMBER CLICKS EMPTY",
  banner_shot: "{n} TAKES THE BULLET",
  banner_was_imposter: "{n} WAS THE IMPOSTER",
  banner_was_innocent: "{n} WAS INNOCENT",
  banner_you_shot: "YOU TAKE THE BULLET",
  win_crew_title: "THE TABLE <span class='accent'>HOLDS</span>",
  win_crew_body: "The imposter, {n}, is face-down in the sawdust. The secret word was “{w}”. The regulars drink to your health.",
  win_imp_title: "THE <span class='accent'>IMPOSTER</span> WINS",
  win_imp_body: "Too many innocents took the bullet. {n} never knew the word was “{w}” — and never needed to.",
  win_you_imp_title: "A <span class='accent'>PERFECT</span> LIE",
  win_you_imp_body: "You bluffed your way through with nothing but “{h}”. The word was “{w}”. Nobody ever knew.",
  lose_you_shot_title: "YOU WERE <span class='accent'>INNOCENT</span>",
  lose_you_shot_body: "The table turned on you. The imposter, {n}, smiles into their glass. The word was “{w}”.",
  lose_you_imp_title: "CAUGHT <span class='accent'>RED-HANDED</span>",
  lose_you_imp_body: "They saw through your bluff. The word you never knew was “{w}”.",
  votes_for: "{c} vote{s}",
  you: "You",
  dead_tag: "✝",
  tut_1: "Everyone says one word per round related to the secret card.",
  tut_2: "Bold words prove you're innocent — but teach the imposter the secret.",
  tut_3: "Sly words protect the secret — but make YOU look like the imposter.",
};
export function fmt(s, vars={}) {
  return s.replace(/\{(\w+)\}/g, (_,k)=> vars[k] !== undefined ? vars[k] : "{"+k+"}");
}
